plugins { id 'com.android.application' }

android { namespace 'com.pcopi.thaitv'; compileSdk 35
    defaultConfig { applicationId 'com.pcopi.thaitv'; minSdk 23; targetSdk 35; versionCode 142; versionName '1.4.2' }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.media3:media3-exoplayer:1.11.0'
    implementation 'androidx.media3:media3-ui:1.11.0'
}
