plugins { id 'com.android.application' }

android {
    namespace 'com.pcopi.thaitv'
    compileSdk 36

    defaultConfig {
        applicationId 'com.pcopi.thaitv'
        minSdk 23
        targetSdk 36
        versionCode 144
        versionName '1.4.4'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.media3:media3-exoplayer:1.11.0'
    implementation 'androidx.media3:media3-ui:1.11.0'
    implementation 'androidx.media3:media3-exoplayer-hls:1.11.0'
}
