package com.pcopi.passwordvault;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.text.*;import android.text.InputType;import android.view.*;import android.widget.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;

public class MainActivityV2 extends Activity{
 static final int BLUE=Color.rgb(35,103,245),BG=Color.rgb(247,249,253),TEXT=Color.rgb(27,35,50),MUTED=Color.rgb(105,116,133);
 VaultStore store;String master="";LinearLayout root,list;EditText search;ProgressDialog pd;
 int d(float x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}
 TextView tv(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
 GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(d(r));return g;}
 GradientDrawable line(){GradientDrawable g=bg(Color.WHITE,14);g.setStroke(d(1),Color.rgb(220,226,235));return g;}
 EditText in(String hint){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(true);e.setTextSize(15);e.setTextColor(TEXT);e.setHintTextColor(Color.rgb(145,153,165));e.setPadding(d(14),0,d(14),0);e.setBackground(line());return e;}
 Button bt(String s){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackground(bg(BLUE,14));return b;}
 void shell(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);setContentView(root);}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);store=new VaultStore(this);if(store.initialized())lock();else setup();}
 @Override protected void onStop(){super.onStop();if(!isChangingConfigurations())master="";}
 LinearLayout card(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(d(18),d(16),d(18),d(16));x.setBackground(bg(Color.WHITE,20));return x;}
 void setup(){shell();root.addView(tv("🔐",55,BLUE),new LinearLayout.LayoutParams(-1,d(100)));TextView h=tv("My Password Vault",27,TEXT);h.setGravity(17);h.setTypeface(null,1);root.addView(h,new LinearLayout.LayoutParams(-1,d(48)));TextView s=tv("จัดเก็บ Username และ Password อย่างปลอดภัย",15,MUTED);s.setGravity(17);root.addView(s,new LinearLayout.LayoutParams(-1,d(42)));LinearLayout box=card();LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,d(205));bp.setMargins(d(18),d(18),d(18),0);root.addView(box,bp);EditText p=in("สร้าง Master Password อย่างน้อย 6 ตัวอักษร");p.setInputType(129);box.addView(p,new LinearLayout.LayoutParams(-1,d(54)));EditText c=in("ยืนยัน Master Password");c.setInputType(129);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,d(54));cp.setMargins(0,d(10),0,0);box.addView(c,cp);Button go=bt("เริ่มใช้งาน");LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(-1,d(50));gp.setMargins(0,d(12),0,0);box.addView(go,gp);go.setOnClickListener(v->{String a=p.getText().toString(),x=c.getText().toString();if(a.length()<6){p.setError("อย่างน้อย 6 ตัวอักษร");return;}if(!a.equals(x)){c.setError("รหัสไม่ตรงกัน");return;}try{store.initialize(a);master=a;home();}catch(Exception e){toast("สร้าง Vault ไม่สำเร็จ: "+e.getMessage());}});}
 void lock(){shell();root.addView(tv("🔒",55,BLUE),new LinearLayout.LayoutParams(-1,d(105)));TextView h=tv("My Password Vault",26,TEXT);h.setGravity(17);h.setTypeface(null,1);root.addView(h,new LinearLayout.LayoutParams(-1,d(45)));TextView s=tv("กรุณาใส่ Master Password เพื่อเข้าใช้งาน",15,MUTED);s.setGravity(17);root.addView(s,new LinearLayout.LayoutParams(-1,d(45)));LinearLayout b=card();LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,d(145));bp.setMargins(d(18),d(18),d(18),0);root.addView(b,bp);EditText p=in("Master Password");p.setInputType(129);b.addView(p,new LinearLayout.LayoutParams(-1,d(54)));Button go=bt("🔓  เข้าสู่ระบบ");LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(-1,d(50));gp.setMargins(0,d(10),0,0);b.addView(go,gp);go.setOnClickListener(v->{String x=p.getText().toString();if(store.unlock(x)){master=x;home();}else p.setError("รหัสผ่านไม่ถูกต้อง");});}
 void top(String title,View.OnClickListener back){LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(d(10),0,d(12),0);TextView b=tv("‹",36,TEXT);b.setGravity(17);h.addView(b,new LinearLayout.LayoutParams(d(48),d(58)));TextView t=tv(title,20,TEXT);t.setTypeface(null,1);h.addView(t,new LinearLayout.LayoutParams(0,d(58),1));root.addView(h);b.setOnClickListener(back);}
 void home(){shell();LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(d(15),0,d(10),0);TextView logo=tv("🔐",25,BLUE);h.addView(logo,new LinearLayout.LayoutParams(d(45),d(55)));TextView t=tv("My Password Vault",19,TEXT);t.setTypeface(null,1);h.addView(t,new LinearLayout.LayoutParams(0,d(55),1));TextView l=tv("🔒",20,MUTED);h.addView(l,new LinearLayout.LayoutParams(d(45),d(55)));root.addView(h);l.setOnClickListener(v->{master="";lock();});search=in("🔎  ค้นหา ชื่อรายการ, username หรือหมายเหตุ...");LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,d(50));sp.setMargins(d(14),d(3),d(14),d(8));root.addView(search,sp);search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){render(s.toString());}public void afterTextChanged(Editable e){}});list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);ScrollView sv=new ScrollView(this);sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));Button add=bt("＋  เพิ่มรายการ");LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,d(54));ap.setMargins(d(14),d(6),d(14),d(6));root.addView(add,ap);add.setOnClickListener(v->edit(null));LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);nav.setBackgroundColor(Color.WHITE);String[] n={"รายการ","หมวดหมู่","สำรองข้อมูล","ตั้งค่า"};for(int i=0;i<4;i++){TextView q=tv(n[i],11,MUTED);q.setGravity(17);final int z=i;nav.addView(q,new LinearLayout.LayoutParams(0,d(54),1));q.setOnClickListener(v->{if(z==0)home();else if(z==1)categories();else if(z==2)backup();else settings();});}root.addView(nav);render("");}
 void render(String q){list.removeAllViews();q=q.toLowerCase(Locale.ROOT);int no=0;for(VaultStore.Entry e:store.entries(master)){if(!(e.title+" "+e.user+" "+e.note+" "+e.category).toLowerCase(Locale.ROOT).contains(q))continue;no++;LinearLayout c=card();c.setOrientation(LinearLayout.HORIZONTAL);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(d(10),d(5),d(8),d(5));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,d(76));cp.setMargins(d(12),d(4),d(12),d(4));list.addView(c,cp);TextView num=tv(String.format(Locale.US,"%02d",no),12,BLUE);num.setGravity(17);num.setBackground(bg(Color.rgb(230,239,255),40));c.addView(num,new LinearLayout.LayoutParams(d(38),d(38)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.setPadding(d(12),0,0,0);TextView a=tv(e.title,16,TEXT);a.setTypeface(null,1);tx.addView(a,new LinearLayout.LayoutParams(-1,d(31)));tx.addView(tv(e.user.isEmpty()?"ไม่มี Username":e.user,12,MUTED),new LinearLayout.LayoutParams(-1,d(25)));c.addView(tx,new LinearLayout.LayoutParams(0,-1,1));c.addView(tv("›",29,MUTED),new LinearLayout.LayoutParams(d(30),-1));c.setOnClickListener(v->details(e));}if(no==0){TextView z=tv("ยังไม่มีรายการ\nกด “เพิ่มรายการ” เพื่อเริ่มต้น",16,MUTED);z.setGravity(17);list.addView(z,new LinearLayout.LayoutParams(-1,d(160)));}}
 void details(VaultStore.Entry e){shell();top("รายละเอียดรายการ",v->home());LinearLayout b=card();LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(d(14),d(8),d(14),d(14));root.addView(b,bp);TextView h=tv(e.title,23,TEXT);h.setTypeface(null,1);b.addView(h,new LinearLayout.LayoutParams(-1,d(50)));field(b,"Username",e.user,true,false);field(b,"Password",e.pass,true,true);field(b,"บันทึกเพิ่มเติม",e.note,false,false);field(b,"หมวดหมู่",e.category,false,false);Button ed=bt("✎  แก้ไข");b.addView(ed,new LinearLayout.LayoutParams(-1,d(52)));ed.setOnClickListener(v->edit(e));Button del=bt("ลบรายการ");del.setTextColor(Color.rgb(190,45,60));del.setBackground(line());LinearLayout.LayoutParams dp=new LinearLayout.LayoutParams(-1,d(52));dp.setMargins(0,d(10),0,0);b.addView(del,dp);del.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("ลบรายการ?").setMessage(e.title).setNegativeButton("ยกเลิก",null).setPositiveButton("ลบ",(x,w)->{try{store.delete(master,e.id);home();}catch(Exception z){toast("ลบไม่สำเร็จ");}}).show());}
 void field(LinearLayout b,String lab,String value,boolean copy,boolean pw){b.addView(tv(lab,12,MUTED),new LinearLayout.LayoutParams(-1,d(28)));LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(d(12),0,d(4),0);r.setBackground(line());TextView v=tv(pw?"••••••••••":(value.isEmpty()?"-":value),15,TEXT);r.addView(v,new LinearLayout.LayoutParams(0,d(50),1));if(pw){TextView eye=tv("👁",18,MUTED);r.addView(eye,new LinearLayout.LayoutParams(d(42),d(50)));eye.setOnClickListener(x->v.setText(v.getText().toString().startsWith("•")?value:"••••••••••"));}if(copy){TextView cp=tv("📋",18,MUTED);r.addView(cp,new LinearLayout.LayoutParams(d(42),d(50)));cp.setOnClickListener(x->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText(lab,value));toast("คัดลอกแล้ว");});}b.addView(r,new LinearLayout.LayoutParams(-1,d(52)));}
 void edit(VaultStore.Entry old){VaultStore.Entry e=old==null?VaultStore.newEntry():new VaultStore.Entry(old.id,old.title,old.user,old.pass,old.note,old.category);shell();top(old==null?"เพิ่มรายการ":"แก้ไขรายการ",v->home());ScrollView sv=new ScrollView(this);LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(d(16),d(4),d(16),d(18));sv.addView(b);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));EditText a=in("ชื่อรายการ");a.setText(e.title);b.addView(tv("รายการ",12,MUTED));b.addView(a,new LinearLayout.LayoutParams(-1,d(52)));EditText u=in("Username");u.setText(e.user);b.addView(tv("Username",12,MUTED));b.addView(u,new LinearLayout.LayoutParams(-1,d(52)));EditText p=in("Password");p.setText(e.pass);p.setInputType(129);b.addView(tv("Password",12,MUTED));b.addView(p,new LinearLayout.LayoutParams(-1,d(52)));EditText n=in("บันทึกเพิ่มเติม");n.setSingleLine(false);n.setMinLines(3);n.setGravity(Gravity.TOP);n.setText(e.note);b.addView(tv("บันทึกเพิ่มเติม",12,MUTED));b.addView(n,new LinearLayout.LayoutParams(-1,d(90)));EditText cat=in("เช่น ทั่วไป / อีเมล / ธนาคาร");cat.setText(e.category);b.addView(tv("หมวดหมู่",12,MUTED));b.addView(cat,new LinearLayout.LayoutParams(-1,d(52)));Button save=bt("💾  บันทึก");LinearLayout.LayoutParams sb=new LinearLayout.LayoutParams(-1,d(54));sb.setMargins(0,d(18),0,0);b.addView(save,sb);save.setOnClickListener(v->{e.title=a.getText().toString().trim();e.user=u.getText().toString();e.pass=p.getText().toString();e.note=n.getText().toString();e.category=cat.getText().toString();if(e.title.isEmpty()){a.setError("กรุณาระบุชื่อรายการ");return;}try{if(old==null)store.add(master,e);else store.update(master,e);home();}catch(Exception x){toast("บันทึกไม่สำเร็จ");}});}
 void categories(){shell();top("หมวดหมู่",v->home());LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(d(14),d(8),d(14),d(20));root.addView(b);Map<String,Integer> m=new LinkedHashMap<>();for(VaultStore.Entry e:store.entries(master)){String c=e.category==null||e.category.isEmpty()?"ทั่วไป":e.category;m.put(c,m.getOrDefault(c,0)+1);}if(m.isEmpty())b.addView(tv("ยังไม่มีหมวดหมู่",15,MUTED),new LinearLayout.LayoutParams(-1,d(100)));for(Map.Entry<String,Integer>x:m.entrySet()){LinearLayout r=card();r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);TextView n=tv("▦  "+x.getKey(),16,TEXT);r.addView(n,new LinearLayout.LayoutParams(0,d(62),1));r.addView(tv(String.valueOf(x.getValue()),14,MUTED),new LinearLayout.LayoutParams(d(40),d(62)));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,d(68));rp.setMargins(0,d(5),0,d(5));b.addView(r,rp);}}
 void backup(){shell();top("สำรองและกู้คืน",v->home());LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(d(14),d(8),d(14),d(20));ScrollView sv=new ScrollView(this);sv.addView(b);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));TextView info=tv("🔐 Backup เข้ารหัสด้วย Master Password\nเลือก Google Drive, NAS หรือโฟลเดอร์ปลายทางได้จากตัวเลือกไฟล์",14,TEXT);info.setPadding(d(14),d(12),d(14),d(12));info.setBackground(bg(Color.rgb(231,241,255),15));b.addView(info,new LinearLayout.LayoutParams(-1,d(82)));Button ex=bt("☁  สำรองข้อมูล / เลือกที่เก็บ");b.addView(ex,new LinearLayout.LayoutParams(-1,d(54)));ex.setOnClickListener(v->exportFile());Button im=bt("♻  กู้คืนข้อมูล / เลือกไฟล์ Backup");im.setTextColor(BLUE);im.setBackground(line());LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(-1,d(54));ip.setMargins(0,d(10),0,d(18));b.addView(im,ip);im.setOnClickListener(v->importFile());TextView sh=tv("NAS / Synology",19,TEXT);sh.setTypeface(null,1);b.addView(sh,new LinearLayout.LayoutParams(-1,d(40)));TextView nt=tv("ไม่ต้องกรอก IP หรือรหัสผ่าน NAS ในแอป\nตอนสำรอง/กู้คืนให้เลือกตำแหน่ง NAS จากตัวจัดการไฟล์ของเครื่อง หาก NAS ถูกเพิ่มไว้ในแอปไฟล์",13,MUTED);b.addView(nt,new LinearLayout.LayoutParams(-1,d(70)));}
 void exportFile(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/octet-stream");i.addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_TITLE,"MyPasswordVault_Backup.mpv");startActivityForResult(i,10);}
 void importFile(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,11);}
 @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(c!=RESULT_OK||data==null)return;try{if(r==10){String x=store.encryptedBackup(master);try(OutputStream o=getContentResolver().openOutputStream(data.getData())){if(o==null)throw new IOException("เปิดไฟล์ปลายทางไม่ได้");o.write(x.getBytes(StandardCharsets.UTF_8));}toast("Backup สำเร็จ");}else if(r==11){askBackupPassword(readText(data.getData()));}}catch(Exception e){toast("ดำเนินการไม่สำเร็จ: "+e.getMessage());}}
 String readText(android.net.Uri uri)throws Exception{StringBuilder s=new StringBuilder();InputStream raw=getContentResolver().openInputStream(uri);if(raw==null)throw new IOException("เปิดไฟล์ไม่ได้");try(InputStream in=raw;BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){String z;while((z=br.readLine())!=null)s.append(z).append('\n');}return s.toString();}
 void askBackupPassword(String backup){EditText p=in("Master Password ที่ใช้สร้าง Backup");p.setInputType(129);LinearLayout box=new LinearLayout(this);box.setPadding(d(6),d(4),d(6),0);box.addView(p,new LinearLayout.LayoutParams(-1,d(54)));new AlertDialog.Builder(this).setTitle("รหัสผ่านของ Backup").setMessage("กรุณาใส่ Master Password เดิมที่ใช้ตอนกด Backup\n\nถ้าคุณเปลี่ยน Master Password หลังติดตั้งใหม่ ก็ยัง Restore ได้").setView(box).setNegativeButton("ยกเลิก",null).setPositiveButton("ตรวจสอบและกู้คืน",(d,w)->{String bp=p.getText().toString();if(bp.isEmpty()){toast("กรุณากรอกรหัสผ่าน Backup");return;}confirmRestore(backup,bp);}).show();}
 void confirmRestore(String backup,String backupPassword){new AlertDialog.Builder(this).setTitle("ยืนยันการกู้คืน").setMessage("ข้อมูลในเครื่องจะถูกแทนที่ด้วย Backup นี้\n\nระบบจะตรวจสอบรหัสผ่านและข้อมูลก่อน จากนั้นจะเข้ารหัสใหม่ด้วย Master Password ปัจจุบัน").setNegativeButton("ยกเลิก",null).setPositiveButton("กู้คืน",(d,w)->{try{store.restoreEncryptedBackup(backup,backupPassword,master);toast("กู้คืนสำเร็จ");home();}catch(Exception e){toast("กู้คืนไม่สำเร็จ: "+friendlyRestoreError(e));}}).show();}
 String friendlyRestoreError(Exception e){String m=e.getMessage();if(m==null)return "ไฟล์หรือรหัสผ่านไม่ถูกต้อง";if(m.contains("AEADBadTag")||m.contains("bad tag")||m.contains("IllegalArgumentException"))return "รหัสผ่าน Backup ไม่ถูกต้อง หรือไฟล์เสียหาย";if(m.contains("JSON"))return "Backup เสียหายหรือรูปแบบไม่ถูกต้อง";return m;}
 void settings(){shell();top("ตั้งค่า",v->home());LinearLayout b=card();LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(d(14),d(10),d(14),d(14));root.addView(b,bp);b.addView(tv("🔐 ความปลอดภัย",19,TEXT),new LinearLayout.LayoutParams(-1,d(48)));Button l=bt("🔒 ล็อกแอปทันที");b.addView(l,new LinearLayout.LayoutParams(-1,d(52)));l.setOnClickListener(v->{master="";lock();});TextView note=tv("V2.2\nข้อมูล Vault เข้ารหัสในเครื่อง\nBackup/Restore ใช้ตัวเลือกไฟล์ของ Android จึงสามารถเลือก Google Drive หรือ NAS ได้ตามที่เครื่องรองรับ",13,MUTED);note.setPadding(0,d(18),0,0);b.addView(note,new LinearLayout.LayoutParams(-1,d(120)));}
}
