package com.pcopi.passwordvault;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.text.InputType;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import java.io.*;
import java.util.*;

public class MainActivity extends Activity {
    static final int BLUE=Color.rgb(21,101,255), BG=Color.rgb(247,249,252), TEXT=Color.rgb(28,37,54), MUTED=Color.rgb(105,116,133);
    VaultStore store; String master=""; boolean unlocked=false; LinearLayout root,content; EditText search; List<VaultStore.Entry> all=new ArrayList<>();
    final int REQ_EXPORT=201, REQ_IMPORT=202;
    int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,float size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setGravity(Gravity.CENTER_VERTICAL);return t;}
    GradientDrawable bg(int color,float r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(r));return g;} GradientDrawable stroke(int color,int line,float r){GradientDrawable g=bg(Color.WHITE,r);g.setStroke(dp(line),color);return g;}
    Button btn(String text){Button b=new Button(this);b.setText(text);b.setTextSize(14);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackground(bg(BLUE,14));b.setPadding(dp(18),0,dp(18),0);return b;}
    EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(15);e.setTextColor(TEXT);e.setHintTextColor(Color.rgb(150,158,170));e.setSingleLine(false);e.setPadding(dp(14),dp(3),dp(14),dp(3));e.setBackground(stroke(Color.rgb(222,227,235),1,12));return e;}
    LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    TextView label(String s){TextView t=tv(s,12,MUTED);t.setPadding(dp(2),dp(10),0,dp(5));return t;}

    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);store=new VaultStore(this);if(!store.initialized())showCreateMaster();else showLock();}
    @Override protected void onStop(){super.onStop();if(unlocked){unlocked=false;master="";}}

    void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);setContentView(root);}
    void showCreateMaster(){base();Space top=new Space(this);root.addView(top,new LinearLayout.LayoutParams(1,dp(55)));TextView icon=tv("🔐",55,BLUE);icon.setGravity(Gravity.CENTER);root.addView(icon,new LinearLayout.LayoutParams(-1,dp(75)));TextView title=tv("My Password Vault",27,TEXT);title.setGravity(Gravity.CENTER);title.setTypeface(null,1);root.addView(title,new LinearLayout.LayoutParams(-1,dp(50)));TextView sub=tv("เก็บรหัสผ่านของคุณอย่างปลอดภัย",16,MUTED);sub.setGravity(Gravity.CENTER);root.addView(sub,new LinearLayout.LayoutParams(-1,dp(40)));LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(22),dp(15),dp(22),dp(15));box.setBackground(bg(Color.WHITE,20));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(220));bp.setMargins(dp(20),dp(25),dp(20),0);root.addView(box,bp);EditText p=field("สร้าง Master Password");p.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);box.addView(p,new LinearLayout.LayoutParams(-1,dp(55)));EditText c=field("ยืนยัน Master Password");c.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);box.addView(c,new LinearLayout.LayoutParams(-1,dp(55)));TextView hint=tv("ใช้รหัสผ่านที่เดายาก และอย่าลืมเก็บไว้ในที่ปลอดภัย",12,MUTED);hint.setPadding(dp(4),dp(10),0,dp(10));box.addView(hint);Button go=btn("เริ่มใช้งาน");box.addView(go,new LinearLayout.LayoutParams(-1,dp(50)));go.setOnClickListener(v->{String a=p.getText().toString(),d=c.getText().toString();if(a.length()<6){toast("Master Password อย่างน้อย 6 ตัวอักษร");return;}if(!a.equals(d)){toast("รหัสผ่านยืนยันไม่ตรงกัน");return;}try{store.initialize(a);master=a;unlocked=true;showVault();}catch(Exception e){toast("สร้าง Vault ไม่สำเร็จ");}});}

    void showLock(){base();Space s=new Space(this);root.addView(s,new LinearLayout.LayoutParams(1,dp(70)));TextView ic=tv("🔒",55,BLUE);ic.setGravity(Gravity.CENTER);root.addView(ic,new LinearLayout.LayoutParams(-1,dp(75)));TextView title=tv("My Password Vault",26,TEXT);title.setTypeface(null,1);title.setGravity(Gravity.CENTER);root.addView(title,new LinearLayout.LayoutParams(-1,dp(45)));TextView sub=tv("กรุณาใส่รหัสผ่านเพื่อเข้าใช้งาน",15,MUTED);sub.setGravity(Gravity.CENTER);root.addView(sub,new LinearLayout.LayoutParams(-1,dp(35)));LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(22),dp(20),dp(22),dp(20));box.setBackground(bg(Color.WHITE,20));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(150));bp.setMargins(dp(20),dp(25),dp(20),0);root.addView(box,bp);EditText p=field("รหัสผ่าน");p.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);box.addView(p,new LinearLayout.LayoutParams(-1,dp(55)));Button go=btn("เข้าสู่ระบบ");LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(-1,dp(50));gp.setMargins(0,dp(15),0,0);box.addView(go,gp);go.setOnClickListener(v->unlock(p));p.setOnEditorActionListener((v,a,e)->{unlock(p);return true;});p.requestFocus();root.postDelayed(()->((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).showSoftInput(p,InputMethodManager.SHOW_IMPLICIT),250);}
    void unlock(EditText p){String x=p.getText().toString();if(store.unlock(x)){master=x;unlocked=true;((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(p.getWindowToken(),0);showVault();}else{p.setError("รหัสผ่านไม่ถูกต้อง");}}

    void showVault(){base();LinearLayout head=row();head.setPadding(dp(16),dp(8),dp(10),0);TextView menu=tv("☰",27,TEXT);head.addView(menu,new LinearLayout.LayoutParams(dp(42),dp(52)));TextView title=tv("My Password Vault",19,TEXT);title.setTypeface(null,1);head.addView(title,new LinearLayout.LayoutParams(0,dp(52),1));TextView gear=tv("⚙",24,MUTED);head.addView(gear,new LinearLayout.LayoutParams(dp(45),dp(52)));root.addView(head);menu.setOnClickListener(v->showAboutMenu());gear.setOnClickListener(v->showSettings());
        search=field("ค้นหาชื่อ, username, หมายเหตุ...");search.setSingleLine(true);search.setCompoundDrawablesWithIntrinsicBounds(android.R.drawable.ic_menu_search,0,0,0);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(50));sp.setMargins(dp(14),dp(3),dp(14),dp(8));root.addView(search,sp);search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){renderList(s.toString());}public void afterTextChanged(android.text.Editable e){}});
        content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));load();renderList("");
        LinearLayout nav=row();nav.setPadding(dp(6),dp(5),dp(6),dp(5));nav.setBackgroundColor(Color.WHITE);String[] ns={"⌂\nรายการ","▦\nหมวดหมู่","☁\nสำรองข้อมูล","⚙\nตั้งค่า"};for(int i=0;i<4;i++){TextView n=tv(ns[i],11,MUTED);n.setGravity(Gravity.CENTER);final int z=i;nav.addView(n,new LinearLayout.LayoutParams(0,dp(62),1));n.setOnClickListener(v->{if(z==0)showVault();else if(z==1)showCategories();else if(z==2)showBackup();else showSettings();});}root.addView(nav);TextView add=tv("+",30,Color.WHITE);add.setGravity(Gravity.CENTER);add.setBackground(bg(BLUE,50));add.setElevation(dp(7));FrameLayout decor=new FrameLayout(this);decor.setClickable(false);add.setClickable(true);add.setOnClickListener(v->editEntry(null));add.setLayoutParams(new FrameLayout.LayoutParams(dp(58),dp(58),Gravity.RIGHT|Gravity.BOTTOM));add.setTranslationY(-dp(82));add.setTranslationX(-dp(18));add.setZ(20);root.addView(add);}
    void load(){all=store.entries(master);}
    void renderList(String q){if(content==null)return;content.removeAllViews();load();q=q==null?"":q.toLowerCase(Locale.ROOT);int no=0;for(VaultStore.Entry e:all){String hay=(e.title+" "+e.user+" "+e.note).toLowerCase(Locale.ROOT);if(!hay.contains(q))continue;no++;addCard(e,no);}if(no==0){TextView empty=tv("ยังไม่มีรายการ\nกดปุ่ม + เพื่อเพิ่ม Username และ Password",16,MUTED);empty.setGravity(Gravity.CENTER);empty.setPadding(dp(20),dp(80),dp(20),0);content.addView(empty,new LinearLayout.LayoutParams(-1,dp(170)));}}
    void addCard(VaultStore.Entry e,int no){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.HORIZONTAL);card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(14),dp(8),dp(8),dp(8));card.setBackground(bg(Color.WHITE,16));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(78));cp.setMargins(dp(12),dp(5),dp(12),dp(5));content.addView(card,cp);TextView num=tv(String.format(Locale.US,"%02d",no),13,BLUE);num.setGravity(Gravity.CENTER);num.setBackground(bg(Color.rgb(231,239,255),30));card.addView(num,new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout text=new LinearLayout(this);text.setOrientation(LinearLayout.VERTICAL);text.setPadding(dp(12),0,0,0);TextView t=tv(e.title.isEmpty()?"ไม่มีชื่อรายการ":e.title,16,TEXT);t.setTypeface(null,1);text.addView(t,new LinearLayout.LayoutParams(-1,dp(29)));TextView u=tv(e.user,13,MUTED);text.addView(u,new LinearLayout.LayoutParams(-1,dp(25)));card.addView(text,new LinearLayout.LayoutParams(0,-1,1));TextView more=tv("⋮",26,MUTED);more.setGravity(Gravity.CENTER);card.addView(more,new LinearLayout.LayoutParams(dp(38),-1));View.OnClickListener open=v->showDetails(e);card.setOnClickListener(open);more.setOnClickListener(v->showEntryActions(e));}

    void showDetails(VaultStore.Entry e){base();topBar("รายละเอียดรายการ",()->showVault());LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(18),dp(18),dp(18));box.setBackground(bg(Color.WHITE,18));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(dp(14),dp(15),dp(14),dp(8));root.addView(box,bp);TextView h=tv(e.title,23,TEXT);h.setTypeface(null,1);box.addView(h,new LinearLayout.LayoutParams(-1,dp(48)));detailRow(box,"Username",e.user,true);detailRow(box,"Password",e.pass,true);detailRow(box,"บันทึกเพิ่มเติม",e.note,false);detailRow(box,"หมวดหมู่",e.category,false);Button edit=btn("✎  แก้ไขรายการ");box.addView(edit,new LinearLayout.LayoutParams(-1,dp(50)));edit.setOnClickListener(v->editEntry(e));Button del=btn("ลบรายการ");del.setTextColor(Color.rgb(190,40,55));del.setBackground(stroke(Color.rgb(240,200,205),1,14));LinearLayout.LayoutParams dp1=new LinearLayout.LayoutParams(-1,dp(50));dp1.setMargins(0,dp(10),0,0);box.addView(del,dp1);del.setOnClickListener(v->confirmDelete(e));}
    void detailRow(LinearLayout box,String lab,String value,boolean copy){box.addView(label(lab));LinearLayout r=row();r.setPadding(dp(12),0,dp(5),0);r.setBackground(stroke(Color.rgb(230,234,240),1,12));TextView v=tv(value.isEmpty()?"-":value,15,TEXT);if(lab.equals("Password"))v.setText("••••••••••");r.addView(v,new LinearLayout.LayoutParams(0,dp(50),1));if(lab.equals("Password")){TextView eye=tv("👁",20,MUTED);r.addView(eye,new LinearLayout.LayoutParams(dp(42),dp(50)));eye.setOnClickListener(x->{v.setText(v.getText().toString().startsWith("•")?value:"••••••••••");});}if(copy){TextView c=tv("📋",18,MUTED);r.addView(c,new LinearLayout.LayoutParams(dp(42),dp(50)));c.setOnClickListener(x->copy(value));}box.addView(r,new LinearLayout.LayoutParams(-1,dp(52)));}

    void editEntry(VaultStore.Entry original){final VaultStore.Entry e=original==null?VaultStore.newEntry():new VaultStore.Entry(original.id,original.title,original.user,original.pass,original.note,original.category);base();topBar(original==null?"เพิ่มรายการใหม่":"แก้ไขรายการ",()->showVault());LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(10),dp(18),dp(20));ScrollView sv=new ScrollView(this);sv.addView(box);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));EditText title=field("ชื่อรายการ เช่น Facebook");setVal(title,e.title);box.addView(label("รายการ"));box.addView(title,new LinearLayout.LayoutParams(-1,dp(52)));EditText user=field("Username");setVal(user,e.user);box.addView(label("Username"));box.addView(user,new LinearLayout.LayoutParams(-1,dp(52)));LinearLayout pw=row();EditText pass=field("Password");pass.setSingleLine(true);pass.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);setVal(pass,e.pass);pw.addView(pass,new LinearLayout.LayoutParams(0,dp(52),1));TextView eye=tv("👁",19,MUTED);eye.setGravity(Gravity.CENTER);pw.addView(eye,new LinearLayout.LayoutParams(dp(50),dp(52)));eye.setOnClickListener(v->{int pos=pass.getSelectionStart();boolean hidden=(pass.getInputType()&(InputType.TYPE_TEXT_VARIATION_PASSWORD))!=0;pass.setInputType(InputType.TYPE_CLASS_TEXT|(hidden?InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD:InputType.TYPE_TEXT_VARIATION_PASSWORD));pass.setSelection(Math.max(0,pos));});box.addView(label("Password"));box.addView(pw,new LinearLayout.LayoutParams(-1,dp(52)));EditText note=field("รายละเอียดเพิ่มเติม");note.setMinLines(3);setVal(note,e.note);box.addView(label("บันทึกเพิ่มเติม"));box.addView(note,new LinearLayout.LayoutParams(-1,dp(95)));EditText cat=field("หมวดหมู่ (เช่น ทั่วไป, อีเมล, ธนาคาร)");setVal(cat,e.category);box.addView(label("หมวดหมู่"));box.addView(cat,new LinearLayout.LayoutParams(-1,dp(52)));Button save=btn("💾  บันทึก");LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(52));sp.setMargins(0,dp(18),0,dp(10));box.addView(save,sp);save.setOnClickListener(v->{e.title=title.getText().toString().trim();e.user=user.getText().toString();e.pass=pass.getText().toString();e.note=note.getText().toString();e.category=cat.getText().toString().trim();if(e.title.isEmpty()){title.setError("กรุณาระบุรายการ");return;}try{if(original==null)store.add(master,e);else store.update(master,e);toast("บันทึกเรียบร้อย");showVault();}catch(Exception ex){toast("บันทึกไม่สำเร็จ");}});}
    void setVal(EditText e,String s){e.setText(s==null?"":s);}
    void topBar(String title,Runnable back){LinearLayout h=row();h.setPadding(dp(8),dp(6),dp(12),0);TextView b=tv("‹",38,TEXT);b.setGravity(Gravity.CENTER);h.addView(b,new LinearLayout.LayoutParams(dp(45),dp(52)));TextView t=tv(title,20,TEXT);t.setTypeface(null,1);h.addView(t,new LinearLayout.LayoutParams(0,dp(52),1));root.addView(h);b.setOnClickListener(v->back.run());}

    void showCategories(){base();topBar("หมวดหมู่",()->showVault());LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(12),dp(14),dp(20));root.addView(box);load();Map<String,Integer> m=new LinkedHashMap<>();for(VaultStore.Entry e:all){String c=e.category==null||e.category.isEmpty()?"ทั่วไป":e.category;m.put(c,m.containsKey(c)?m.get(c)+1:1);}if(m.isEmpty()){TextView e=tv("ยังไม่มีข้อมูล",16,MUTED);e.setGravity(Gravity.CENTER);box.addView(e,new LinearLayout.LayoutParams(-1,dp(120)));}for(String k:m.keySet()){LinearLayout c=row();c.setPadding(dp(15),0,dp(12),0);c.setBackground(bg(Color.WHITE,16));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(70));p.setMargins(0,dp(5),0,dp(5));box.addView(c,p);TextView n=tv("▦",22,BLUE);c.addView(n,new LinearLayout.LayoutParams(dp(40),dp(60)));TextView name=tv(k,16,TEXT);c.addView(name,new LinearLayout.LayoutParams(0,dp(60),1));TextView count=tv(String.valueOf(m.get(k)),14,MUTED);c.addView(count,new LinearLayout.LayoutParams(dp(40),dp(60));}}

    void showBackup(){base();topBar("สำรองข้อมูล",()->showVault());LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(8),dp(14),dp(20));root.addView(box);TextView info=tv("ข้อมูลสำรองจะถูกเข้ารหัส ไม่สามารถอ่าน Username/Password ได้โดยไม่มี Master Password",14,TEXT);info.setPadding(dp(14),dp(14),dp(14),dp(14));info.setBackground(bg(Color.rgb(232,241,255),15));box.addView(info,new LinearLayout.LayoutParams(-1,dp(88)));Button gd=btn("☁  สำรองไป Google Drive / ไฟล์");box.addView(gd,new LinearLayout.LayoutParams(-1,dp(54)));gd.setOnClickListener(v->exportBackup());Button restore=btn("♻  กู้คืนจาก Google Drive / ไฟล์");restore.setTextColor(BLUE);restore.setBackground(stroke(Color.rgb(185,207,255),1,14));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(54));rp.setMargins(0,dp(10),0,dp(18));box.addView(restore,rp);restore.setOnClickListener(v->importBackup());TextView st=tv("Synology NAS (WebDAV)",18,TEXT);st.setTypeface(null,1);box.addView(st);EditText url=field("URL WebDAV เช่น https://nas.example.com:5006/backup");box.addView(label("ที่อยู่ NAS"));box.addView(url,new LinearLayout.LayoutParams(-1,dp(52)));EditText user=field("Username");box.addView(label("ชื่อผู้ใช้"));box.addView(user,new LinearLayout.LayoutParams(-1,dp(52)));EditText pass=field("Password");pass.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);box.addView(label("รหัสผ่าน NAS"));box.addView(pass,new LinearLayout.LayoutParams(-1,dp(52)));Button up=btn("☁  เชื่อมต่อและสำรองข้อมูล");LinearLayout.LayoutParams upP=new LinearLayout.LayoutParams(-1,dp(54));upP.setMargins(0,dp(16),0,dp(10));box.addView(up,upP);up.setOnClickListener(v->new Thread(()->{try{String name="PasswordManager_"+new java.text.SimpleDateFormat("yyyyMMdd_HHmmss",Locale.US).format(new Date())+".pmb";BackupManager.upload(url.getText().toString(),user.getText().toString(),pass.getText().toString(),name,store.encryptedBackup(master));runOnUiThread(()->toast("สำรองข้อมูลไป Synology สำเร็จ"));}catch(Exception ex){runOnUiThread(()->toast("สำรอง NAS ไม่สำเร็จ: "+ex.getMessage()));}}).start());TextView tip=tv("หมายเหตุ: Synology ต้องเปิด WebDAV และใช้ HTTPS เมื่อเชื่อมต่อจากอินเทอร์เน็ต",12,MUTED);box.addView(tip);}
    void exportBackup(){try{String data=store.encryptedBackup(master);Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/octet-stream");i.putExtra(Intent.EXTRA_TITLE,"PasswordManager_Backup.pmb");pending=data;startActivityForResult(i,REQ_EXPORT);}catch(Exception e){toast("สร้าง Backup ไม่สำเร็จ");}}
    void importBackup(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,REQ_IMPORT);}
    String pending="";
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;try{if(r==REQ_EXPORT){try(OutputStream o=getContentResolver().openOutputStream(d.getData())){o.write(pending.getBytes("UTF-8"));}toast("บันทึก Backup สำเร็จ");}else if(r==REQ_IMPORT){try(InputStream in=getContentResolver().openInputStream(d.getData());ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);store.restoreEncryptedBackup(out.toString("UTF-8"),master);}toast("กู้คืนข้อมูลสำเร็จ");showVault();}}catch(Exception e){toast("ดำเนินการไม่สำเร็จ: "+e.getMessage());}}

    void showSettings(){base();topBar("ตั้งค่า",()->showVault());LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(10),dp(14),dp(20));root.addView(box);TextView sec=tv("ความปลอดภัย",18,TEXT);sec.setTypeface(null,1);box.addView(sec,new LinearLayout.LayoutParams(-1,dp(50)));Button change=btn("🔑  เปลี่ยน Master Password");box.addView(change,new LinearLayout.LayoutParams(-1,dp(54)));change.setOnClickListener(v->changeMaster());TextView lock=tv("🔒  แอปจะล็อกทุกครั้งเมื่อออกจากแอป",14,MUTED);lock.setPadding(dp(5),dp(18),0,dp(18));box.addView(lock);TextView about=tv("เกี่ยวกับแอป",18,TEXT);about.setTypeface(null,1);box.addView(about,new LinearLayout.LayoutParams(-1,dp(50)));TextView ver=tv("My Password Vault\nVersion 1.0 • เก็บข้อมูลแบบเข้ารหัส AES-GCM",14,MUTED);box.addView(ver,new LinearLayout.LayoutParams(-1,dp(75)));}
    void changeMaster(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(20),0,dp(20),0);EditText old=field("Master Password เดิม");old.setInputType(129);EditText n=field("Master Password ใหม่");n.setInputType(129);EditText c=field("ยืนยันรหัสใหม่");c.setInputType(129);l.addView(old);l.addView(n);l.addView(c);new AlertDialog.Builder(this).setTitle("เปลี่ยน Master Password").setView(l).setNegativeButton("ยกเลิก",null).setPositiveButton("บันทึก",(d,w)->{if(!store.unlock(old.getText().toString())){toast("Master Password เดิมไม่ถูกต้อง");return;}if(n.getText().length()<6||!n.getText().toString().equals(c.getText().toString())){toast("รหัสใหม่ไม่ตรงกันหรือสั้นเกินไป");return;}try{List<VaultStore.Entry> es=store.entries(master);store.initialize(n.getText().toString());store.saveEntries(n.getText().toString(),es);master=n.getText().toString();toast("เปลี่ยนรหัสผ่านสำเร็จ");}catch(Exception e){toast("เปลี่ยนรหัสผ่านไม่สำเร็จ");}}).show();}
    void showEntryActions(VaultStore.Entry e){new AlertDialog.Builder(this).setItems(new String[]{"ดูรายละเอียด","แก้ไข","ลบ"},(d,w)->{if(w==0)showDetails(e);else if(w==1)editEntry(e);else confirmDelete(e);}).show();}
    void confirmDelete(VaultStore.Entry e){new AlertDialog.Builder(this).setTitle("ลบรายการ?").setMessage("ต้องการลบ "+e.title+" หรือไม่").setNegativeButton("ยกเลิก",null).setPositiveButton("ลบ",(d,w)->{try{store.delete(master,e.id);showVault();}catch(Exception x){toast("ลบไม่สำเร็จ");}}).show();}
    void showAboutMenu(){new AlertDialog.Builder(this).setItems(new String[]{"＋ เพิ่มรายการ","☁ สำรองข้อมูล","⚙ ตั้งค่า","เกี่ยวกับ My Password Vault"},(d,w)->{if(w==0)editEntry(null);else if(w==1)showBackup();else if(w==2)showSettings();else new AlertDialog.Builder(this).setTitle("My Password Vault").setMessage("แอปจัดเก็บ Username และ Password ส่วนตัว\nข้อมูลในเครื่องถูกเข้ารหัส").setPositiveButton("ตกลง",null).show();}).show();}
    void copy(String s){((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("Password Vault",s));toast("คัดลอกแล้ว");}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
