package com.pcopi.thaitv;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.database.Cursor;import android.graphics.*;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import android.util.Size;import android.view.*;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import androidx.media3.common.*;import androidx.media3.exoplayer.ExoPlayer;import androidx.media3.ui.PlayerView;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;import java.util.regex.*;
public class MainActivityV24 extends AppCompatActivity{
 int BG=Color.rgb(12,12,14),PANEL=Color.rgb(25,25,28),CARD=Color.rgb(37,37,42),TEXT=Color.WHITE,MUTED=Color.rgb(170,170,175); LinearLayout root,content,nav,playerBox;PlayerView pv;ExoPlayer player;TextView title,status;SharedPreferences pref;Spinner group;EditText search;ArrayAdapter<String> channelAdapter;ArrayList<C> channels=new ArrayList<>(),shown=new ArrayList<>();ArrayList<F> playlists=new ArrayList<>(),videos=new ArrayList<>(),audios=new ArrayList<>();ExecutorService io=Executors.newSingleThreadExecutor();boolean full=false;int tab=1;final int PERM=91;
 int d(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);} TextView t(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(d(12),d(5),d(12),d(5));return v;} Button b(String s){Button x=new Button(this);x.setText(s);x.setTextColor(TEXT);x.setTextSize(12);x.setAllCaps(false);x.setBackgroundColor(PANEL);return x;}
 @Override public void onCreate(Bundle x){super.onCreate(x);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);pref=getSharedPreferences("thai_tv",0);ui();perm();scan();for(String u:urls())loadUrl(u);}
 void ui(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout top=new LinearLayout(this);top.setBackgroundColor(PANEL);Button m=b("☰");top.addView(m,new LinearLayout.LayoutParams(d(52),d(56)));m.setOnClickListener(v->menu());title=t("Thai TV Player",19,TEXT);title.setTypeface(null,1);top.addView(title,new LinearLayout.LayoutParams(0,d(56),1));Button f=b("⛶");top.addView(f,new LinearLayout.LayoutParams(d(52),d(56)));f.setOnClickListener(v->full());root.addView(top);playerBox=new LinearLayout(this);playerBox.setBackgroundColor(Color.BLACK);pv=new PlayerView(this);pv.setUseController(true);playerBox.addView(pv,new LinearLayout.LayoutParams(-1,d(220)));root.addView(playerBox);status=t("พร้อมใช้งาน",12,MUTED);root.addView(status,new LinearLayout.LayoutParams(-1,d(30)));content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);String[] n={"▣\nวิดีโอ","▤\nPlaylist","⌕\nเรียกดู","♫\nเสียง","⋮\nอื่นๆ"};for(int i=0;i<5;i++){final int q=i;Button z=b(n[i]);z.setTextSize(11);nav.addView(z,new LinearLayout.LayoutParams(0,d(66),1));z.setOnClickListener(v->tab(q));}root.addView(nav,new LinearLayout.LayoutParams(-1,d(66)));setContentView(root);player=new ExoPlayer.Builder(this).build();pv.setPlayer(player);player.addListener(new Player.Listener(){public void onPlayerError(PlaybackException e){status.setText("เปิดไม่ได้: "+e.getErrorCodeName());}});tab(1);}
 void menu(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(d(8),d(16),d(8),d(8));String[] a={"วิดีโอ","Playlist","เรียกดู","เสียง","อื่นๆ","เปิด M3U / M3U8","เพิ่ม URL Playlist"};AlertDialog q=new AlertDialog.Builder(this).setTitle("Thai TV Player").setView(x).create();for(int i=0;i<a.length;i++){final int k=i;Button z=b(a[i]);x.addView(z,new LinearLayout.LayoutParams(-1,d(50)));z.setOnClickListener(v->{q.dismiss();if(k==5)pick();else if(k==6)urlDialog(false);else tab(k);});}q.show();}
 void tab(int n){tab=n;content.removeAllViews();if(n==0)mediaPage(videos,true,"วิดีโอ");else if(n==1)playlistPage();else if(n==2)browse();else if(n==3)mediaPage(audios,false,"เสียง");else other();}
 void mediaPage(ArrayList<F> a,boolean vid,String h){content.addView(t(h,19,TEXT),new LinearLayout.LayoutParams(-1,d(45)));ScrollView s=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);for(F f:a){LinearLayout r=new LinearLayout(this);ImageView im=new ImageView(this);im.setBackgroundColor(CARD);im.setScaleType(ImageView.ScaleType.CENTER_CROP);r.addView(im,new LinearLayout.LayoutParams(d(112),d(72)));LinearLayout q=new LinearLayout(this);q.setOrientation(LinearLayout.VERTICAL);q.addView(t(f.name,15,TEXT));q.addView(t(vid?"วิดีโอ":"เสียง",11,MUTED));r.addView(q,new LinearLayout.LayoutParams(0,d(78),1));box.addView(r,new LinearLayout.LayoutParams(-1,d(80)));r.setOnClickListener(v->playLocal(f.uri));if(vid&&Build.VERSION.SDK_INT>=29)io.execute(()->{try{Bitmap z=getContentResolver().loadThumbnail(f.uri,new Size(d(112),d(72)),null);runOnUiThread(()->im.setImageBitmap(z));}catch(Exception e){}});}s.addView(box);content.addView(s,new LinearLayout.LayoutParams(-1,0,1));}
 void playlistPage(){LinearLayout tools=new LinearLayout(this);Button p=b("📄 M3U/M3U8"),u=b("🌐 URL"),r=b("↻ สแกน");tools.addView(p,new LinearLayout.LayoutParams(0,d(48),1));tools.addView(u,new LinearLayout.LayoutParams(0,d(48),1));tools.addView(r,new LinearLayout.LayoutParams(0,d(48),1));content.addView(tools);p.setOnClickListener(v->pick());u.setOnClickListener(v->urlDialog(false));r.setOnClickListener(v->scan());content.addView(t("PLAYLIST ทั้งหมด • แตะเพื่อโหลด/เล่น",14,MUTED));ScrollView s=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);for(F f:playlists)row(box,"📄 "+f.name,"ไฟล์ในเครื่อง",()->readLocal(f.uri));for(String z:urls())row(box,"🌐 "+z,"URL",()->loadUrl(z));s.addView(box);content.addView(s,new LinearLayout.LayoutParams(-1,d(175)));search=new EditText(this);search.setSingleLine();search.setHint("ค้นหาช่อง…");search.setTextColor(TEXT);search.setHintTextColor(MUTED);search.setBackgroundColor(PANEL);content.addView(search,new LinearLayout.LayoutParams(-1,d(48)));group=new Spinner(this);content.addView(group,new LinearLayout.LayoutParams(-1,d(44)));ListView list=new ListView(this);channelAdapter=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,new ArrayList<>());list.setAdapter(channelAdapter);list.setOnItemClickListener((a,v,pos,id)->{String n=channelAdapter.getItem(pos);for(C c:shown)if(c.name.equals(n)){play(c.url,c.name);break;}});content.addView(list,new LinearLayout.LayoutParams(-1,0,1));search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){filter();}public void afterTextChanged(Editable e){}});groups();filter();}
 void row(LinearLayout box,String a,String sub,Runnable r){Button z=b(a+"\n"+sub);z.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);box.addView(z,new LinearLayout.LayoutParams(-1,d(58)));z.setOnClickListener(v->r.run());}
 void browse(){content.addView(t("เรียกดู",19,TEXT));act("📄 เปิด M3U / M3U8",v->pick());act("↻ สแกน Playlist / Video / Audio",v->scan());act("🎬 วิดีโอ",v->tab(0));act("♫ เสียง",v->tab(3));}
 void other(){content.addView(t("อื่นๆ",19,TEXT));act("▶ เปิด M3U8 URL โดยตรง",v->urlDialog(true));act("↻ โหลด URL ทั้งหมด",v->{for(String z:urls())loadUrl(z);});act("⚙ ล้าง URL",v->new AlertDialog.Builder(this).setMessage("ล้าง URL ทั้งหมด?").setNegativeButton("ยกเลิก",null).setPositiveButton("ล้าง",(d,w)->{pref.edit().remove("urls").apply();tab(1);}).show());}
 void act(String s,View.OnClickListener l){Button z=b(s);z.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);content.addView(z,new LinearLayout.LayoutParams(-1,d(56)));z.setOnClickListener(l);}
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,1001);}
 @Override protected void onActivityResult(int r,int c,Intent x){super.onActivityResult(r,c,x);if(r==1001&&c==RESULT_OK&&x!=null&&x.getData()!=null){Uri u=x.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);}catch(Exception e){}saveFile(u);readLocal(u);}}
 void urlDialog(boolean direct){EditText e=new EditText(this);e.setSingleLine();e.setTextColor(TEXT);e.setHintTextColor(MUTED);e.setHint("https://example.com/playlist.m3u8");new AlertDialog.Builder(this).setTitle(direct?"เปิด M3U8 URL":"เพิ่ม URL Playlist").setView(e).setNegativeButton("ยกเลิก",null).setPositiveButton(direct?"เปิด":"เพิ่มและโหลด",(d,w)->{String z=e.getText().toString().trim();if(z.isEmpty())return;if(direct)play(z,"M3U8");else{saveUrl(z);loadUrl(z);}}).show();}
 LinkedHashSet<String> urls(){LinkedHashSet<String>s=new LinkedHashSet<>();for(String z:pref.getString("urls","").split("\\n"))if(!z.trim().isEmpty())s.add(z.trim());String old=pref.getString("playlist_url","").trim();if(!old.isEmpty())s.add(old);return s;}void saveUrl(String z){LinkedHashSet<String>s=urls();s.add(z);StringBuilder b=new StringBuilder();for(String q:s)b.append(q).append('\n');pref.edit().putString("urls",b.toString()).apply();}
 void saveFile(Uri u){String n=name(u);LinkedHashMap<String,String>m=new LinkedHashMap<>();for(F f:playlists)m.put(f.uri.toString(),f.name);m.put(u.toString(),n);pref.edit().putString("files",enc(m)).apply();playlists.clear();for(Map.Entry<String,String>e:m.entrySet())playlists.add(new F(e.getValue(),Uri.parse(e.getKey())));}
 String enc(Map<String,String>m){StringBuilder b=new StringBuilder();for(Map.Entry<String,String>e:m.entrySet())b.append(e.getKey()).append('|').append(e.getValue().replace("|"," ")).append('\n');return b.toString();}String name(Uri u){try(Cursor c=getContentResolver().query(u,new String[]{MediaStore.MediaColumns.DISPLAY_NAME},null,null,null)){if(c!=null&&c.moveToFirst())return c.getString(0);}catch(Exception e){}return "M3U8";}
 void readLocal(Uri u){io.execute(()->{try{String s=read(u);if(hls(s)){runOnUiThread(()->play(u.toString(),name(u)));return;}ArrayList<C> q=parse(s,u.toString());if(q.isEmpty()){runOnUiThread(()->toast("ไม่พบรายการช่องในไฟล์"));return;}runOnUiThread(()->merge(q,name(u)));}catch(Exception e){runOnUiThread(()->toast("อ่าน M3U/M3U8 ไม่สำเร็จ"));}});}
 String read(Uri u)throws Exception{InputStream in=getContentResolver().openInputStream(u);if(in==null)throw new Exception();BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String x;while((x=r.readLine())!=null)b.append(x).append('\n');r.close();return b.toString();}boolean hls(String s){String z=s.toUpperCase(Locale.ROOT);return z.contains("#EXT-X-TARGETDURATION")||z.contains("#EXT-X-MEDIA-SEQUENCE");}
 void loadUrl(String z){saveUrl(z);io.execute(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(z).openConnection();c.setInstanceFollowRedirects(true);c.setConnectTimeout(20000);c.setReadTimeout(30000);c.setRequestProperty("User-Agent","Mozilla/5.0");int code=c.getResponseCode();InputStream in=code>=400?c.getErrorStream():c.getInputStream();String s=stream(in);if(hls(s)){runOnUiThread(()->play(z,"M3U8"));return;}ArrayList<C> q=parse(s,z);runOnUiThread(()->{if(q.isEmpty())play(z,"M3U8");else merge(q,z);});}catch(Exception e){runOnUiThread(()->play(z,"M3U8"));}});}
 String stream(InputStream in)throws Exception{if(in==null)throw new Exception();BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String x;while((x=r.readLine())!=null)b.append(x).append('\n');r.close();return b.toString();}
 ArrayList<C> parse(String s,String base){ArrayList<C>o=new ArrayList<>();String n=null,l="",g="ทั่วไป",id="";for(String raw:s.replace("\uFEFF","").replace("\r","").split("\\n")){String x=raw.trim();if(x.isEmpty())continue;if(x.regionMatches(true,0,"#EXTINF",0,7)){int k=x.indexOf(',');String inf=k>0?x.substring(0,k):x;n=k>0?x.substring(k+1).trim():"ช่อง";l=at(inf,"tvg-logo");g=at(inf,"group-title");id=at(inf,"tvg-id");if(g.isEmpty())g="ทั่วไป";}else if(n!=null&&!x.startsWith("#")){o.add(new C(n,resolve(base,x),l,g,id));n=null;}else if(!x.startsWith("#")&&(x.startsWith("http://")||x.startsWith("https://")))o.add(new C(x,x,"","ทั่วไป",""));}return o;}
 String at(String s,String k){Matcher m=Pattern.compile(k+"\\s*=\\s*\\\"([^\\\"]*)\\\"",Pattern.CASE_INSENSITIVE).matcher(s);return m.find()?m.group(1):"";}String resolve(String base,String x){try{if(x.startsWith("http://")||x.startsWith("https://"))return x;if(base.startsWith("http://")||base.startsWith("https://"))return new URL(new URL(base),x).toString();}catch(Exception e){}return x;}
 void merge(ArrayList<C>q,String src){channels.clear();channels.addAll(q);status.setText("โหลด "+q.size()+" ช่อง • "+src);tab(1);}void groups(){if(group==null)return;LinkedHashSet<String>s=new LinkedHashSet<>();s.add("ทั้งหมด");for(C c:channels)s.add(c.g);group.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new ArrayList<>(s)));group.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?>p){}public void onItemSelected(AdapterView<?>p,View v,int x,long id){filter();}});}
 void filter(){if(channelAdapter==null)return;shown.clear();String q=search==null?"":search.getText().toString().toLowerCase(Locale.ROOT);String g=group==null||group.getSelectedItem()==null?"ทั้งหมด":group.getSelectedItem().toString();ArrayList<String>n=new ArrayList<>();for(C c:channels)if((g.equals("ทั้งหมด")||c.g.equals(g))&&(q.isEmpty()||c.name.toLowerCase(Locale.ROOT).contains(q)||c.url.toLowerCase(Locale.ROOT).contains(q)||c.id.toLowerCase(Locale.ROOT).contains(q))){shown.add(c);n.add(c.name);}channelAdapter.clear();channelAdapter.addAll(n);}
 void play(String u,String n){try{player.stop();MediaItem.Builder m=new MediaItem.Builder().setUri(u);String z=u.toLowerCase(Locale.ROOT);if(z.contains("m3u8")||z.endsWith(".m3u")||z.contains("playlist"))m.setMimeType(MimeTypes.APPLICATION_M3U8);player.setMediaItem(m.build());player.prepare();player.play();title.setText(n);status.setText("กำลังเล่น • "+u);}catch(Exception e){toast("เปิดไม่ได้");}}
 void playLocal(Uri u){try{player.stop();player.setMediaItem(MediaItem.fromUri(u));player.prepare();player.play();title.setText("กำลังเล่น");}catch(Exception e){toast("เล่นไฟล์ไม่ได้");}}
 void full(){full=!full;if(full){setRequestedOrientation(0);getWindow().getDecorView().setSystemUiVisibility(5894);playerBox.getLayoutParams().height=-1;playerBox.requestLayout();content.setVisibility(View.GONE);nav.setVisibility(View.GONE);status.setVisibility(View.GONE);}else{setRequestedOrientation(-1);getWindow().getDecorView().setSystemUiVisibility(0);playerBox.getLayoutParams().height=d(220);playerBox.requestLayout();content.setVisibility(View.VISIBLE);nav.setVisibility(View.VISIBLE);status.setVisibility(View.VISIBLE);}}
 @Override public void onBackPressed(){if(full){full();return;}super.onBackPressed();}@Override protected void onDestroy(){try{player.stop();player.release();}catch(Exception e){}io.shutdownNow();super.onDestroy();}
 void perm(){if(Build.VERSION.SDK_INT>=33){if(checkSelfPermission(Manifest.permission.READ_MEDIA_VIDEO)!=PackageManager.PERMISSION_GRANTED||checkSelfPermission(Manifest.permission.READ_MEDIA_AUDIO)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.READ_MEDIA_VIDEO,Manifest.permission.READ_MEDIA_AUDIO},PERM);}else if(checkSelfPermission(Manifest.permission.READ_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.READ_EXTERNAL_STORAGE},PERM);}
 void scan(){io.execute(()->{media(MediaStore.Video.Media.EXTERNAL_CONTENT_URI,videos);media(MediaStore.Audio.Media.EXTERNAL_CONTENT_URI,audios);playFiles();runOnUiThread(()->tab(tab));});}
 void media(Uri base,ArrayList<F>out){try(Cursor c=getContentResolver().query(base,new String[]{MediaStore.MediaColumns._ID,MediaStore.MediaColumns.DISPLAY_NAME},null,null,MediaStore.MediaColumns.DATE_ADDED+" DESC")){if(c==null)return;out.clear();while(c.moveToNext()){long id=c.getLong(0);out.add(new F(c.getString(1),ContentUris.withAppendedId(base,id)));if(out.size()>=300)break;}}catch(Exception e){}}
 void playFiles(){try{LinkedHashMap<String,F>a=new LinkedHashMap<>();Uri base=MediaStore.Files.getContentUri("external");String s=MediaStore.MediaColumns.DISPLAY_NAME+" LIKE ? OR "+MediaStore.MediaColumns.DISPLAY_NAME+" LIKE ? OR "+MediaStore.MediaColumns.DISPLAY_NAME+" LIKE ?";String[]q={"%.m3u","%.M3U","%.m3u8"};try(Cursor c=getContentResolver().query(base,new String[]{MediaStore.MediaColumns._ID,MediaStore.MediaColumns.DISPLAY_NAME},s,q,MediaStore.MediaColumns.DATE_ADDED+" DESC")){if(c!=null)while(c.moveToNext()){long id=c.getLong(0);a.put(String.valueOf(id),new F(c.getString(1),ContentUris.withAppendedId(base,id)));}}for(String x:pref.getString("files","").split("\\n")){int p=x.indexOf('|');if(p>0)a.put(x.substring(0,p),new F(x.substring(p+1),Uri.parse(x.substring(0,p))));}playlists.clear();playlists.addAll(a.values());}catch(Exception e){}}
 static class C{String name,url,logo,g,id;C(String a,String b,String c,String d,String e){name=a;url=b;logo=c;g=d;id=e;}}static class F{String name;Uri uri;F(String n,Uri u){name=n;uri=u;}}void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
