package com.pcopi.thaitv;
import android.app.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.view.*;import android.widget.*;import androidx.media3.common.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.lang.reflect.*;import java.util.*;
public class MainActivityV26 extends MainActivityV21{
 @Override void makeUi(){drawer=new androidx.drawerlayout.widget.DrawerLayout(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.BLACK);topBar=new LinearLayout(this);Button m=button("☰");topBar.addView(m,new LinearLayout.LayoutParams(dp(52),dp(56)));m.setOnClickListener(v->drawer.openDrawer(side));title=text("Thai TV Player",19,TEXT);topBar.addView(title,new LinearLayout.LayoutParams(0,dp(56),1));Button f=button("⛶");topBar.addView(f,new LinearLayout.LayoutParams(dp(52),dp(56)));f.setOnClickListener(v->full26());root.addView(topBar);playerView=new androidx.media3.ui.PlayerView(this);playerView.setUseController(true);playerView.setBackgroundColor(Color.BLACK);root.addView(playerView,new LinearLayout.LayoutParams(-1,dp(220)));status=text("พร้อมใช้งาน",12,MUTED);root.addView(status,new LinearLayout.LayoutParams(-1,dp(30)));content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));nav();makeSide();drawer.addView(root,new androidx.drawerlayout.widget.DrawerLayout.LayoutParams(-1,-1));drawer.addView(side,new androidx.drawerlayout.widget.DrawerLayout.LayoutParams(dp(310),-1,Gravity.LEFT));setContentView(drawer);player=new androidx.media3.exoplayer.ExoPlayer.Builder(this).build();playerView.setPlayer(player);player.addListener(new Player.Listener(){public void onPlayerError(PlaybackException e){status.setText("เปิดไม่ได้: "+e.getErrorCodeName());toast("เปิดสตรีมไม่ได้: "+e.getErrorCodeName());}});showTab(1);}
 @Override void showTab(int t){tab=t;content.removeAllViews();if(t==0){mediaTab(false);}else if(t==1){playlist26();}else if(t==2){browse26();}else if(t==3){mediaTab(true);}else other26();}
 void playlist26(){Button f=button("📄 M3U / M3U8"),u=button("🌐 URL Playlist"),r=button("↻ สแกน");LinearLayout bar=new LinearLayout(this);bar.addView(f,new LinearLayout.LayoutParams(0,dp(48),1));bar.addView(u,new LinearLayout.LayoutParams(0,dp(48),1));bar.addView(r,new LinearLayout.LayoutParams(0,dp(48),1));content.addView(bar);f.setOnClickListener(v->pickPlaylist());u.setOnClickListener(v->urlDialog(false));r.setOnClickListener(v->{scanPlaylistFiles();scanMedia();showTab(1);});content.addView(text("PLAYLIST ทั้งหมด • แตะชื่อเพื่อโหลด",15,TEXT));ScrollView sv=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);for(PlaylistFile p:playlistFiles)row26(box,"📄 "+p.name,()->readLocal(Uri.parse(p.uri)));for(String x:savedUrls())row26(box,"🌐 "+x,()->loadUrl26(x));sv.addView(box);content.addView(sv,new LinearLayout.LayoutParams(-1,dp(175)));search=new EditText(this);search.setSingleLine();search.setHint("ค้นหาช่อง / URL / tvg-id");search.setTextColor(TEXT);search.setHintTextColor(MUTED);search.setBackgroundColor(PANEL);content.addView(search,new LinearLayout.LayoutParams(-1,dp(48)));groups=new Spinner(this);content.addView(groups,new LinearLayout.LayoutParams(-1,dp(44)));ListView list=new ListView(this);channelAdapter=new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,new ArrayList<String>());list.setAdapter(channelAdapter);list.setOnItemClickListener((p,v,pos,id)->playObject26(shown.get(pos)));content.addView(list,new LinearLayout.LayoutParams(-1,0,1));search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){filter();}public void afterTextChanged(android.text.Editable e){}});rebuildGroups();filter();}
 void row26(LinearLayout b,String s,Runnable r){Button x=button(s);x.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);b.addView(x,new LinearLayout.LayoutParams(-1,dp(56)));x.setOnClickListener(v->r.run());}
 void browse26(){content.addView(text("เรียกดู",19,TEXT));action26("📄 เปิด M3U / M3U8",v->pickPlaylist());action26("↻ สแกนทั้งหมด",v->{scanPlaylistFiles();scanMedia();});action26("🎬 วิดีโอ",v->showTab(0));action26("♫ เสียง",v->showTab(3));}
 void other26(){content.addView(text("อื่นๆ",19,TEXT));action26("▶ เปิด M3U8 URL โดยตรง",v->urlDialog(true));action26("↻ โหลด URL ทั้งหมด",v->{for(String x:savedUrls())loadUrl26(x);});}
 void action26(String s,View.OnClickListener l){Button b=button(s);b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);content.addView(b,new LinearLayout.LayoutParams(-1,dp(56)));b.setOnClickListener(l);}
 void loadUrl26(String u){saveUrl(u);io.execute(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setInstanceFollowRedirects(true);c.setConnectTimeout(20000);c.setReadTimeout(30000);c.setRequestProperty("User-Agent","Mozilla/5.0");InputStream in=c.getResponseCode()>=400?c.getErrorStream():c.getInputStream();String s=read26(in);if(s.toUpperCase(Locale.ROOT).contains("#EXT-X-TARGETDURATION")){runOnUiThread(()->playUrl26(u,"M3U8"));return;}ArrayList q=parse(s,u);runOnUiThread(()->{if(q.isEmpty())playUrl26(u,"M3U8");else{channels.clear();channels.addAll(q);status.setText("โหลด Playlist URL สำเร็จ: "+q.size()+" ช่อง");showTab(1);}});}catch(Exception e){runOnUiThread(()->playUrl26(u,"M3U8"));}});}
 @Override void readLocal(Uri u){io.execute(()->{try{String s=read26(getContentResolver().openInputStream(u));String z=s.toUpperCase(Locale.ROOT);if(z.contains("#EXT-X-TARGETDURATION")){runOnUiThread(()->playUrl26(u.toString(),"M3U8"));return;}ArrayList q=parse(s,u.toString());runOnUiThread(()->{if(q.isEmpty())toast("ไม่พบช่องในไฟล์ M3U/M3U8");else{channels.clear();channels.addAll(q);status.setText("โหลดไฟล์ Playlist สำเร็จ: "+q.size()+" ช่อง");showTab(1);}});}catch(Exception e){toast("อ่านไฟล์ M3U/M3U8 ไม่สำเร็จ");}});}
 String read26(InputStream in)throws Exception{if(in==null)throw new Exception();BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String x;while((x=r.readLine())!=null)b.append(x).append('\n');r.close();return b.toString();}
 void playObject26(Object ch){try{Field uf=ch.getClass().getDeclaredField("url"),nf=ch.getClass().getDeclaredField("name");uf.setAccessible(true);nf.setAccessible(true);playUrl26(String.valueOf(uf.get(ch)),String.valueOf(nf.get(ch)));}catch(Exception e){toast("อ่านช่องไม่ได้");}}
 void playUrl26(String u,String n){try{player.stop();MediaItem.Builder m=new MediaItem.Builder().setUri(u);String z=u.toLowerCase(Locale.ROOT);if(z.contains("m3u8")||z.contains("playlist")||z.endsWith(".m3u"))m.setMimeType(MimeTypes.APPLICATION_M3U8);player.setMediaItem(m.build());player.prepare();player.play();title.setText(n);status.setText("กำลังเล่น • "+u);}catch(Exception e){toast("เปิดช่องไม่ได้: "+e.getMessage());}}
 void full26(){full=!full;if(full){setRequestedOrientation(android.content.pm.ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);getWindow().getDecorView().setSystemUiVisibility(5894);playerView.getLayoutParams().height=-1;playerView.requestLayout();content.setVisibility(View.GONE);bottomNav.setVisibility(View.GONE);status.setVisibility(View.GONE);}else{setRequestedOrientation(android.content.pm.ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED);getWindow().getDecorView().setSystemUiVisibility(0);playerView.getLayoutParams().height=dp(220);playerView.requestLayout();content.setVisibility(View.VISIBLE);bottomNav.setVisibility(View.VISIBLE);status.setVisibility(View.VISIBLE);}}
}
