package com.pcopi.thaitv;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.graphics.Bitmap;
import android.graphics.Color;
import android.net.Uri;
import android.os.*;
import android.provider.MediaStore;
import android.util.Size;
import android.view.*;
import android.widget.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.media3.common.*;
import androidx.media3.exoplayer.ExoPlayer;
import androidx.media3.ui.PlayerView;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;
import java.util.regex.*;

public class MainActivityV23 extends AppCompatActivity {
  final int BG=Color.rgb(13,13,15), PANEL=Color.rgb(25,25,28), CARD=Color.rgb(35,35,40), TEXT=Color.WHITE, MUTED=Color.rgb(170,170,175), ACCENT=Color.rgb(0,200,83);
  LinearLayout root, content, nav, playerBox; TextView title,status; PlayerView playerView; ExoPlayer player; SharedPreferences prefs;
  final ExecutorService io=Executors.newSingleThreadExecutor(); final ArrayList<Ch> channels=new ArrayList<>();
  final ArrayList<FileItem> playlistFiles=new ArrayList<>(), videos=new ArrayList<>(), audios=new ArrayList<>();
  int currentTab=1; boolean fullscreen=false; Spinner groups; EditText search;
  final ArrayList<Ch> shown=new ArrayList<>(); ArrayAdapter<String> chAdapter; static final int PERM=91;
  int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}
  TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setPadding(dp(12),dp(5),dp(12),dp(5));return t;}
  Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(TEXT);b.setTextSize(13);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setBackgroundColor(PANEL);return b;}
  @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);prefs=getSharedPreferences("thai_tv",0);buildUi();requestPerm();scanAll();loadSavedUrls();}
  void buildUi(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setBackgroundColor(PANEL);Button menu=btn("☰");menu.setTextSize(23);bar.addView(menu,new LinearLayout.LayoutParams(dp(52),dp(56)));menu.setOnClickListener(v->drawer());title=tv("Thai TV Player",19,TEXT);title.setTypeface(null,1);bar.addView(title,new LinearLayout.LayoutParams(0,dp(56),1));Button fs=btn("⛶");fs.setTextSize(22);bar.addView(fs,new LinearLayout.LayoutParams(dp(52),dp(56)));fs.setOnClickListener(v->toggleFull());root.addView(bar);playerBox=new LinearLayout(this);playerBox.setOrientation(LinearLayout.VERTICAL);playerBox.setBackgroundColor(Color.BLACK);playerView=new PlayerView(this);playerView.setUseController(true);playerView.setBackgroundColor(Color.BLACK);playerBox.addView(playerView,new LinearLayout.LayoutParams(-1,dp(220)));root.addView(playerBox);status=tv("พร้อมใช้งาน",12,MUTED);status.setGravity(Gravity.CENTER_VERTICAL);root.addView(status,new LinearLayout.LayoutParams(-1,dp(30)));content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(23,23,26));String[] a={"▣\nวิดีโอ","▤\nPlaylist","⌕\nเรียกดู","♫\nเสียง","⋮\nอื่นๆ"};for(int i=0;i<5;i++){final int n=i;Button q=btn(a[i]);q.setTextSize(11);nav.addView(q,new LinearLayout.LayoutParams(0,dp(66),1));q.setOnClickListener(v->showTab(n));}root.addView(nav,new LinearLayout.LayoutParams(-1,dp(66)));setContentView(root);player=new ExoPlayer.Builder(this).build();playerView.setPlayer(player);player.addListener(new Player.Listener(){public void onPlayerError(PlaybackException e){status.setText("เปิดไม่ได้: "+e.getErrorCodeName());toast("เปิดสตรีมไม่ได้: "+e.getErrorCodeName());}});showTab(1);}
  void drawer(){final PopupWindow p=new PopupWindow(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(10),dp(20),dp(10),dp(10));box.setBackgroundColor(Color.rgb(22,22,25));String[] a={"▣  วิดีโอ","▤  Playlist","⌕  เรียกดู","♫  เสียง","⋮  อื่นๆ","📄  เปิด M3U / M3U8","🌐  เพิ่ม URL Playlist"};for(int i=0;i<a.length;i++){final int n=i;Button b=btn(a[i]);b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);box.addView(b,new LinearLayout.LayoutParams(dp(290),dp(52)));b.setOnClickListener(v->{p.dismiss();if(n==5)pick();else if(n==6)urlDialog(false);else showTab(n);});}p.setContentView(box);p.setWidth(dp(310));p.setHeight(-1);p.setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(Color.TRANSPARENT));p.setOutsideTouchable(true);p.setFocusable(true);p.showAtLocation(root,Gravity.LEFT|Gravity.TOP,0,0);}
  void showTab(int t){currentTab=t;content.removeAllViews();if(t==0)videoPage();else if(t==1)playlistPage();else if(t==2)browsePage();else if(t==3)audioPage();else otherPage();}
  void videoPage(){header("วิดีโอ","วิดีโอในเครื่อง • แตะเพื่อเล่น");mediaGrid(videos,true);} void audioPage(){header("เสียง","ไฟล์เสียงในเครื่อง • แตะเพื่อเล่น");mediaGrid(audios,false);}
  void header(String h,String sub){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.addView(tv(h,19,TEXT),new LinearLayout.LayoutParams(-1,dp(40)));x.addView(tv(sub,12,MUTED),new LinearLayout.LayoutParams(-1,dp(35)));content.addView(x);}
  void mediaGrid(ArrayList<FileItem> list,boolean video){ScrollView sv=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);for(FileItem f:list){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);ImageView im=new ImageView(this);im.setScaleType(ImageView.ScaleType.CENTER_CROP);im.setBackgroundColor(CARD);row.addView(im,new LinearLayout.LayoutParams(dp(112),dp(70)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(tv(f.name,15,TEXT));tx.addView(tv(video?"วิดีโอ":"เสียง",11,MUTED));row.addView(tx,new LinearLayout.LayoutParams(0,dp(76),1));box.addView(row,new LinearLayout.LayoutParams(-1,dp(78)));row.setOnClickListener(v->playLocal(f.uri));if(video)thumb(f.uri,im);}if(list.isEmpty())box.addView(tv("ไม่พบไฟล์ในเครื่อง กด เรียกดู เพื่อสแกนใหม่",14,MUTED),new LinearLayout.LayoutParams(-1,dp(60)));sv.addView(box);content.addView(sv,new LinearLayout.LayoutParams(-1,0,1));}
  void thumb(Uri u,ImageView im){if(Build.VERSION.SDK_INT>=29)io.execute(()->{try{Bitmap b=getContentResolver().loadThumbnail(u,new Size(dp(112),dp(70)),null);runOnUiThread(()->im.setImageBitmap(b));}catch(Exception e){}});}
  void playlistPage(){LinearLayout tools=new LinearLayout(this);Button f=btn("📄 เปิดไฟล์ M3U/M3U8");Button u=btn("🌐 เพิ่ม URL");Button r=btn("↻ สแกนใหม่");tools.addView(f,new LinearLayout.LayoutParams(0,dp(48),1));tools.addView(u,new LinearLayout.LayoutParams(0,dp(48),1));tools.addView(r,new LinearLayout.LayoutParams(0,dp(48),1));content.addView(tools);f.setOnClickListener(v->pick());u.setOnClickListener(v->urlDialog(false));r.setOnClickListener(v->scanAll());content.addView(tv("PLAYLIST • ไฟล์ในเครื่อง + URL ทั้งหมด",14,MUTED),new LinearLayout.LayoutParams(-1,dp(38)));ScrollView sv=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);for(FileItem f1:playlistFiles)playlistRow(box,"📄  "+f1.name,"ไฟล์ในเครื่อง",()->readLocal(f1.uri));for(String u1:savedUrls())playlistRow(box,"🌐  "+u1,"URL Playlist",()->loadUrl(u1));if(playlistFiles.isEmpty()&&savedUrls().isEmpty())box.addView(tv("ยังไม่พบ Playlist",14,MUTED));sv.addView(box);content.addView(sv,new LinearLayout.LayoutParams(-1,dp(190)));search=new EditText(this);search.setSingleLine(true);search.setHint("ค้นหาช่อง…");search.setTextColor(TEXT);search.setHintTextColor(MUTED);search.setBackgroundColor(PANEL);content.addView(search,new LinearLayout.LayoutParams(-1,dp(48)));groups=new Spinner(this);groups.setBackgroundColor(PANEL);content.addView(groups,new LinearLayout.LayoutParams(-1,dp(44)));ListView list=new ListView(this);chAdapter=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,new ArrayList<>());list.setAdapter(chAdapter);list.setOnItemClickListener((p,v,pos,id)->{String key=chAdapter.getItem(pos);for(Ch c:shown)if(c.name.equals(key)){playUrl(c.url,c.name);break;}});content.addView(list,new LinearLayout.LayoutParams(-1,0,1));search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){filter();}public void afterTextChanged(Editable e){}});rebuildGroups();filter();}
  void playlistRow(LinearLayout box,String name,String sub,Runnable r){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(dp(6),0,dp(6),0);row.setBackgroundColor(CARD);row.addView(tv(name,14,TEXT));row.addView(tv(sub,11,MUTED));box.addView(row,new LinearLayout.LayoutParams(-1,dp(60)));row.setOnClickListener(v->r.run());}
  void browsePage(){header("เรียกดู","ไฟล์และ Playlist ที่พบในเครื่อง");action("📄  เปิด M3U / M3U8",v->pick());action("📂  สแกน Playlist",v->scanAll());action("🎬  วิดีโอ",v->showTab(0));action("♫  เสียง",v->showTab(3));}
  void otherPage(){header("อื่นๆ","เครื่องมือและการจัดการ");action("▶  เปิด M3U8 URL โดยตรง",v->urlDialog(true));action("↻  โหลด Playlist ทั้งหมด",v->loadSavedUrls());action("★  รายการโปรด",v->toast("รายการโปรดจะเพิ่มในรุ่นถัดไป"));action("⚙  ล้าง URL ที่บันทึกไว้",v->new AlertDialog.Builder(this).setMessage("ล้าง URL Playlist ทั้งหมดหรือไม่?").setNegativeButton("ยกเลิก",null).setPositiveButton("ล้าง",(d,w)->{prefs.edit().remove("playlist_urls").apply();showTab(1);}).show());}
  void action(String s,View.OnClickListener l){Button b=btn(s);b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);content.addView(b,new LinearLayout.LayoutParams(-1,dp(56)));b.setOnClickListener(l);}
  void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,1001);}
  @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==1001&&c==RESULT_OK&&d!=null&&d.getData()!=null){Uri u=d.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);}catch(Exception e){}savePlaylistFile(u);readLocal(u);}}
  void urlDialog(boolean direct){EditText e=new EditText(this);e.setSingleLine(true);e.setTextColor(TEXT);e.setHintTextColor(MUTED);e.setHint("https://example.com/playlist.m3u8");new AlertDialog.Builder(this).setTitle(direct?"เปิด M3U8 URL":"เพิ่ม URL Playlist").setView(e).setNegativeButton("ยกเลิก",null).setPositiveButton(direct?"เปิด":"เพิ่มและโหลด",(d,w)->{String u=e.getText().toString().trim();if(u.isEmpty())return;if(direct)playUrl(u,"M3U8");else{saveUrl(u);loadUrl(u);}}).show();}
  LinkedHashSet<String> savedUrls(){LinkedHashSet<String>s=new LinkedHashSet<>();for(String x:prefs.getString("playlist_urls","").split("\\n")){x=x.trim();if(!x.isEmpty())s.add(x);}String old=prefs.getString("playlist_url","").trim();if(!old.isEmpty())s.add(old);return s;}
  void saveUrl(String u){LinkedHashSet<String>s=savedUrls();s.add(u);StringBuilder b=new StringBuilder();for(String x:s)b.append(x).append('\n');prefs.edit().putString("playlist_urls",b.toString()).apply();}
  void savePlaylistFile(Uri u){String name="M3U / M3U8";try(Cursor c=getContentResolver().query(u,new String[]{"_display_name"},null,null,null)){if(c!=null&&c.moveToFirst())name=c.getString(0);}catch(Exception e){}LinkedHashMap<String,String>m=new LinkedHashMap<>();for(FileItem f:playlistFiles)m.put(f.uri.toString(),f.name);m.put(u.toString(),name);prefs.edit().putString("playlist_files",encodeFiles(m)).apply();playlistFiles.clear();for(Map.Entry<String,String>e:m.entrySet())playlistFiles.add(new FileItem(e.getValue(),Uri.parse(e.getKey())));}
  String encodeFiles(Map<String,String>m){StringBuilder b=new StringBuilder();for(Map.Entry<String,String>e:m.entrySet())b.append(e.getKey().replace("|"," ")).append('|').append(e.getValue().replace("|"," ")).append('\n');return b.toString();}
  void readLocal(Uri u){io.execute(()->{try{String s=read(u);if(isHlsManifest(s)){runOnUiThread(()->playUrl(u.toString(),nameOf(u)));return;}ArrayList<Ch> c=parse(s,u.toString());if(c.isEmpty()){runOnUiThread(()->toast("ไฟล์นี้ไม่ใช่ M3U Playlist ที่มีช่อง"));return;}runOnUiThread(()->merge(c,nameOf(u)));}catch(Exception e){runOnUiThread(()->toast("อ่านไฟล์ไม่ได้: "+e.getMessage()));}});}
  String read(Uri u)throws Exception{InputStream in=getContentResolver().openInputStream(u);if(in==null)throw new Exception("เปิดไฟล์ไม่ได้");BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String x;while((x=r.readLine())!=null)b.append(x).append('\n');r.close();return b.toString();}
  boolean isHlsManifest(String s){String z=s.toUpperCase(Locale.ROOT);return z.contains("#EXT-X-TARGETDURATION")||z.contains("#EXT-X-MEDIA-SEQUENCE");}
  String nameOf(Uri u){try(Cursor c=getContentResolver().query(u,new String[]{"_display_name"},null,null,null)){if(c!=null&&c.moveToFirst())return c.getString(0);}catch(Exception e){}return "M3U8";}
  void loadUrl(String u){saveUrl(u);io.execute(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setInstanceFollowRedirects(true);c.setConnectTimeout(20000);c.setReadTimeout(30000);c.setRequestProperty("User-Agent","Mozilla/5.0");c.setRequestProperty("Accept","*/*");int code=c.getResponseCode();InputStream in=code>=400?c.getErrorStream():c.getInputStream();String s=readStream(in);if(isHlsManifest(s)){runOnUiThread(()->playUrl(u,"M3U8"));return;}ArrayList<Ch> ch=parse(s,u);if(ch.isEmpty())runOnUiThread(()->playUrl(u,"M3U8"));else runOnUiThread(()->merge(ch,u));}catch(Exception e){runOnUiThread(()->playUrl(u,"M3U8"));}});}
  String readStream(InputStream in)throws Exception{if(in==null)throw new Exception("ไม่มีข้อมูล");BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String x;while((x=r.readLine())!=null)b.append(x).append('\n');r.close();return b.toString();}
  void loadSavedUrls(){for(String u:savedUrls())loadUrl(u);}
  ArrayList<Ch> parse(String s,String base){ArrayList<Ch> out=new ArrayList<>();String name=null,logo="",group="ทั่วไป",id="";for(String raw:s.replace("\uFEFF","").replace("\r","").split("\\n")){String x=raw.trim();if(x.isEmpty())continue;if(x.regionMatches(true,0,"#EXTINF",0,7)){int comma=x.indexOf(',');String info=comma>=0?x.substring(0,comma):x;name=comma>=0?x.substring(comma+1).trim():"ช่อง";logo=attr(info,"tvg-logo");group=attr(info,"group-title");id=attr(info,"tvg-id");if(group.isEmpty())group="ทั่วไป";}else if(name!=null&&!x.startsWith("#")){String u=resolve(base,x);if(u!=null){out.add(new Ch(name,u,logo,group,id));name=null;}}else if(!x.startsWith("#")&&(x.startsWith("http://")||x.startsWith("https://"))){out.add(new Ch(x,x,"","ทั่วไป",""));}}return out;}
  String attr(String s,String k){Matcher m=Pattern.compile(k+"\\s*=\\s*\\\"([^\\\"]*)\\\"",Pattern.CASE_INSENSITIVE).matcher(s);return m.find()?m.group(1):"";}
  String resolve(String base,String x){try{if(x.startsWith("http://")||x.startsWith("https://"))return x;if(base.startsWith("http://")||base.startsWith("https://"))return new URL(new URL(base),x).toString();return x;}catch(Exception e){return x;}}
  void merge(ArrayList<Ch> c,String src){channels.clear();channels.addAll(c);status.setText("โหลด "+c.size()+" ช่อง จาก "+src);showTab(1);}
  void rebuildGroups(){if(groups==null)return;LinkedHashSet<String>s=new LinkedHashSet<>();s.add("ทั้งหมด");for(Ch c:channels)s.add(c.group);ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new ArrayList<>(s));groups.setAdapter(a);groups.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?>p){}public void onItemSelected(AdapterView<?>p,View v,int pos,long id){filter();}});}
  void filter(){if(chAdapter==null)return;shown.clear();String q=search==null?"":search.getText().toString().toLowerCase(Locale.ROOT);String g=groups==null||groups.getSelectedItem()==null?"ทั้งหมด":groups.getSelectedItem().toString();ArrayList<String>names=new ArrayList<>();for(Ch c:channels){if((g.equals("ทั้งหมด")||c.group.equals(g))&&(q.isEmpty()||c.name.toLowerCase(Locale.ROOT).contains(q)||c.url.toLowerCase(Locale.ROOT).contains(q)||c.id.toLowerCase(Locale.ROOT).contains(q))){shown.add(c);names.add(c.name);}}chAdapter.clear();chAdapter.addAll(names);chAdapter.notifyDataSetChanged();}
  void playUrl(String u,String n){try{player.stop();MediaItem.Builder b=new MediaItem.Builder().setUri(u);String z=u.toLowerCase(Locale.ROOT);if(z.contains(".m3u8")||z.contains("m3u8")||z.contains("playlist"))b.setMimeType(MimeTypes.APPLICATION_M3U8);player.setMediaItem(b.build());player.prepare();player.play();title.setText(n==null?"กำลังเล่น":n);status.setText("กำลังเล่น • "+u);}catch(Exception e){toast("เปิดไม่ได้: "+e.getMessage());}}
  void playLocal(Uri u){try{player.stop();player.setMediaItem(MediaItem.fromUri(u));player.prepare();player.play();title.setText("กำลังเล่น");}catch(Exception e){toast("เล่นไฟล์ไม่ได้");}}
  void toggleFull(){fullscreen=!fullscreen;if(fullscreen){setRequestedOrientation(android.content.pm.ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);getWindow().getDecorView().setSystemUiVisibility(5894);playerBox.getLayoutParams().height=-1;playerBox.requestLayout();nav.setVisibility(View.GONE);content.setVisibility(View.GONE);status.setVisibility(View.GONE);}else{setRequestedOrientation(android.content.pm.ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED);getWindow().getDecorView().setSystemUiVisibility(0);playerBox.getLayoutParams().height=dp(220);playerBox.requestLayout();nav.setVisibility(View.VISIBLE);content.setVisibility(View.VISIBLE);status.setVisibility(View.VISIBLE);}}
  @Override public void onBackPressed(){if(fullscreen){toggleFull();return;}super.onBackPressed();}
  @Override protected void onDestroy(){try{player.stop();player.release();}catch(Exception e){}io.shutdownNow();super.onDestroy();}
  void requestPerm(){if(Build.VERSION.SDK_INT>=33){if(checkSelfPermission(Manifest.permission.READ_MEDIA_VIDEO)!=PackageManager.PERMISSION_GRANTED||checkSelfPermission(Manifest.permission.READ_MEDIA_AUDIO)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.READ_MEDIA_VIDEO,Manifest.permission.READ_MEDIA_AUDIO},PERM);}else if(checkSelfPermission(Manifest.permission.READ_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.READ_EXTERNAL_STORAGE},PERM);}
  void scanAll(){io.execute(()->{scanMediaStore(MediaStore.Video.Media.EXTERNAL_CONTENT_URI,videos);scanMediaStore(MediaStore.Audio.Media.EXTERNAL_CONTENT_URI,audios);scanPlaylists();runOnUiThread(()->showTab(currentTab));});}
  void scanMediaStore(Uri base,ArrayList<FileItem> out){try(Cursor c=getContentResolver().query(base,new String[]{MediaStore.MediaColumns._ID,MediaStore.MediaColumns.DISPLAY_NAME},null,null,MediaStore.MediaColumns.DATE_ADDED+" DESC")){if(c==null)return;out.clear();while(c.moveToNext()){long id=c.getLong(0);out.add(new FileItem(c.getString(1),ContentUris.withAppendedId(base,id)));if(out.size()>=300)break;}}catch(Exception e){}}
  void scanPlaylists(){try{LinkedHashMap<String,FileItem> all=new LinkedHashMap<>();Uri base=MediaStore.Files.getContentUri("external");String sel=MediaStore.Files.FileColumns.DISPLAY_NAME+" LIKE ? OR "+MediaStore.Files.FileColumns.DISPLAY_NAME+" LIKE ? OR "+MediaStore.Files.FileColumns.DISPLAY_NAME+" LIKE ?";String[] args={"%.m3u","%.M3U","%.m3u8"};try(Cursor c=getContentResolver().query(base,new String[]{MediaStore.Files.FileColumns._ID,MediaStore.Files.FileColumns.DISPLAY_NAME},sel,args,MediaStore.Files.FileColumns.DATE_ADDED+" DESC")){if(c!=null)while(c.moveToNext())all.put(String.valueOf(c.getLong(0)),new FileItem(c.getString(1),ContentUris.withAppendedId(base,c.getLong(0))));}for(String x:prefs.getString("playlist_files","").split("\\n")){int p=x.indexOf('|');if(p>0)all.put(x.substring(0,p),new FileItem(x.substring(p+1),Uri.parse(x.substring(0,p))));}playlistFiles.clear();playlistFiles.addAll(all.values());prefs.edit().putString("playlist_files",encodeFiles(allAsMap())).apply();}catch(Exception e){}}
  Map<String,String> allAsMap(){LinkedHashMap<String,String>m=new LinkedHashMap<>();for(FileItem f:playlistFiles)m.put(f.uri.toString(),f.name);return m;}
  static class Ch{String name,url,logo,group,id;Ch(String n,String u,String l,String g,String i){name=n;url=u;logo=l;group=g;id=i;}}
  static class FileItem{String name;Uri uri;FileItem(String n,Uri u){name=n;uri=u;}}
  void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
