package com.pcopi.thaitv;
import android.app.*;import android.content.*;import android.net.Uri;import android.graphics.Color;import android.os.*;import android.view.*;import android.widget.*;import androidx.media3.common.*;import androidx.media3.exoplayer.ExoPlayer;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.regex.*;
public class MainActivityV25 extends MainActivityV21{
 @Override void makeUi(){drawer=new androidx.drawerlayout.widget.DrawerLayout(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.BLACK);topBar=new LinearLayout(this);topBar.setGravity(Gravity.CENTER_VERTICAL);topBar.setBackgroundColor(Color.rgb(22,22,22));Button m=button("☰");topBar.addView(m,new LinearLayout.LayoutParams(dp(52),dp(56)));m.setOnClickListener(v->drawer.openDrawer(side));title=text("Thai TV Player",19,TEXT);topBar.addView(title,new LinearLayout.LayoutParams(0,dp(56),1));Button f=button("⛶");topBar.addView(f,new LinearLayout.LayoutParams(dp(52),dp(56)));f.setOnClickListener(v->full());root.addView(topBar);playerView=new androidx.media3.ui.PlayerView(this);playerView.setUseController(true);playerView.setBackgroundColor(Color.BLACK);root.addView(playerView,new LinearLayout.LayoutParams(-1,dp(220)));status=text("พร้อมใช้งาน",12,MUTED);root.addView(status,new LinearLayout.LayoutParams(-1,dp(30)));content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));nav();makeSide();drawer.addView(root,new androidx.drawerlayout.widget.DrawerLayout.LayoutParams(-1,-1));drawer.addView(side,new androidx.drawerlayout.widget.DrawerLayout.LayoutParams(dp(310),-1,Gravity.LEFT));setContentView(drawer);player=new ExoPlayer.Builder(this).build();playerView.setPlayer(player);player.addListener(new Player.Listener(){public void onPlayerError(PlaybackException e){status.setText("เปิดไม่ได้: "+e.getErrorCodeName());toast("เปิดสตรีมไม่ได้: "+e.getErrorCodeName());}});showTab(1);}
 @Override void showTab(int t){tab=t;content.removeAllViews();if(t==0){mediaTab(false);}else if(t==1){playlistV25();}else if(t==2){browseV25();}else if(t==3){mediaTab(true);}else otherV25();}
 void playlistV25(){LinearLayout tools=new LinearLayout(this);Button a=button("📄 M3U/M3U8"),b=button("🌐 URL"),c=button("↻");tools.addView(a,new LinearLayout.LayoutParams(0,dp(48),1));tools.addView(b,new LinearLayout.LayoutParams(0,dp(48),1));tools.addView(c,new LinearLayout.LayoutParams(0,dp(48),1));content.addView(tools);a.setOnClickListener(v->pickPlaylist());b.setOnClickListener(v->urlDialog(false));c.setOnClickListener(v->{scanPlaylistFiles();loadSavedAll();});content.addView(text("PLAYLIST ทั้งหมด",15,TEXT));LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);for(PlaylistFile p:playlistFiles){Button z=button("📄 "+p.name);z.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);box.addView(z,new LinearLayout.LayoutParams(-1,dp(54)));z.setOnClickListener(v->readLocal(Uri.parse(p.uri)));}for(String u:savedUrlsV25()){Button z=button("🌐 "+u);z.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);box.addView(z,new LinearLayout.LayoutParams(-1,dp(54)));z.setOnClickListener(v->loadUrl(u));}ScrollView s=new ScrollView(this);s.addView(box);content.addView(s,new LinearLayout.LayoutParams(-1,dp(170)));search=new EditText(this);search.setSingleLine(true);search.setHint("ค้นหาช่อง / URL / tvg-id");search.setTextColor(TEXT);search.setHintTextColor(MUTED);search.setBackgroundColor(PANEL);content.addView(search,new LinearLayout.LayoutParams(-1,dp(48)));groups=new Spinner(this);content.addView(groups,new LinearLayout.LayoutParams(-1,dp(44)));ListView list=new ListView(this);channelAdapter=new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,new ArrayList<String>());list.setAdapter(channelAdapter);list.setOnItemClickListener((p,v,pos,id)->{String n=channelAdapter.getItem(pos);for(Channel ch:shown)if(ch.name.equals(n)){playV25(ch.url,ch.name);break;}});content.addView(list,new LinearLayout.LayoutParams(-1,0,1));search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){filter();}public void afterTextChanged(android.text.Editable e){}});rebuildGroups();filter();}
 void browseV25(){content.addView(text("เรียกดู",19,TEXT));actionV25("📄 เปิด M3U / M3U8",v->pickPlaylist());actionV25("↻ สแกนไฟล์ใหม่",v->{scanPlaylistFiles();scanMedia();});actionV25("🎬 วิดีโอ",v->showTab(0));actionV25("♫ เสียง",v->showTab(3));}
 void otherV25(){content.addView(text("อื่นๆ",19,TEXT));actionV25("▶ เปิด M3U8 URL โดยตรง",v->urlDialog(true));actionV25("↻ โหลด URL ทั้งหมด",v->{for(String u:savedUrlsV25())loadUrl(u);});}
 void actionV25(String s,View.OnClickListener l){Button b=button(s);b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);content.addView(b,new LinearLayout.LayoutParams(-1,dp(56)));b.setOnClickListener(l);}
 LinkedHashSet<String> savedUrlsV25(){LinkedHashSet<String>s=new LinkedHashSet<>();for(String u:prefs.getString("playlist_urls","").split("\\n"))if(!u.trim().isEmpty())s.add(u.trim());String old=prefs.getString("playlist_url","").trim();if(!old.isEmpty())s.add(old);return s;}
 void readLocal(Uri u){io.execute(()->{try{String s=readV25(u);String z=s.toUpperCase(Locale.ROOT);if(z.contains("#EXT-X-TARGETDURATION")||z.contains("#EXT-X-MEDIA-SEQUENCE")){runOnUiThread(()->playV25(u.toString(),nameV25(u)));return;}ArrayList<Channel> q=parseV25(s,u.toString());runOnUiThread(()->{if(q.isEmpty())toast("ไม่พบช่องใน M3U/M3U8");else{channels.clear();channels.addAll(q);status.setText("โหลด "+q.size()+" ช่อง จาก "+nameV25(u));showTab(1);}});}catch(Exception e){toast("อ่านไฟล์ M3U/M3U8 ไม่สำเร็จ");}});}
 String readV25(Uri u)throws Exception{InputStream in=getContentResolver().openInputStream(u);if(in==null)throw new Exception();BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String x;while((x=r.readLine())!=null)b.append(x).append('\n');r.close();return b.toString();}
 String nameV25(Uri u){try{android.database.Cursor c=getContentResolver().query(u,new String[]{"_display_name"},null,null,null);if(c!=null){if(c.moveToFirst()){String n=c.getString(0);c.close();return n;}c.close();}}catch(Exception e){}return "M3U8";}
 ArrayList<Channel> parseV25(String s,String base){ArrayList<Channel>o=new ArrayList<>();String n=null,l="",g="ทั่วไป",id="";for(String raw:s.replace("\uFEFF","").replace("\r","").split("\\n")){String x=raw.trim();if(x.isEmpty())continue;if(x.regionMatches(true,0,"#EXTINF",0,7)){int k=x.indexOf(',');String info=k>=0?x.substring(0,k):x;n=k>=0?x.substring(k+1).trim():"ช่อง";l=attrV25(info,"tvg-logo");g=attrV25(info,"group-title");id=attrV25(info,"tvg-id");if(g.isEmpty())g="ทั่วไป";}else if(n!=null&&!x.startsWith("#")){o.add(new Channel(n,resolveV25(base,x),l,g,id));n=null;}else if(!x.startsWith("#")&&(x.startsWith("http://")||x.startsWith("https://")))o.add(new Channel(x,x,"","ทั่วไป",""));}return o;}
 String attrV25(String s,String k){Matcher m=Pattern.compile(k+"\\s*=\\s*\\\"([^\\\"]*)\\\"",Pattern.CASE_INSENSITIVE).matcher(s);return m.find()?m.group(1):"";}String resolveV25(String base,String x){try{if(x.startsWith("http://")||x.startsWith("https://"))return x;if(base.startsWith("http://")||base.startsWith("https://"))return new URL(new URL(base),x).toString();}catch(Exception e){}return x;}
 void loadUrl(String u){saveUrlV25(u);io.execute(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setInstanceFollowRedirects(true);c.setConnectTimeout(20000);c.setReadTimeout(30000);c.setRequestProperty("User-Agent","Mozilla/5.0");int code=c.getResponseCode();InputStream in=code>=400?c.getErrorStream():c.getInputStream();String s=readStreamV25(in);String z=s.toUpperCase(Locale.ROOT);if(z.contains("#EXT-X-TARGETDURATION")||z.contains("#EXT-X-MEDIA-SEQUENCE")){runOnUiThread(()->playV25(u,"M3U8"));return;}ArrayList<Channel>q=parseV25(s,u);runOnUiThread(()->{if(q.isEmpty())playV25(u,"M3U8");else{channels.clear();channels.addAll(q);status.setText("โหลด "+q.size()+" ช่องจาก URL");showTab(1);}});}catch(Exception e){runOnUiThread(()->playV25(u,"M3U8"));}});}
 String readStreamV25(InputStream in)throws Exception{if(in==null)throw new Exception();BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String x;while((x=r.readLine())!=null)b.append(x).append('\n');r.close();return b.toString();}
 void saveUrlV25(String u){LinkedHashSet<String>s=savedUrlsV25();s.add(u);StringBuilder b=new StringBuilder();for(String x:s)b.append(x).append('\n');prefs.edit().putString("playlist_urls",b.toString()).apply();}
 void playV25(String u,String n){try{player.stop();MediaItem.Builder m=new MediaItem.Builder().setUri(u);String z=u.toLowerCase(Locale.ROOT);if(z.contains("m3u8")||z.contains("playlist")||z.endsWith(".m3u"))m.setMimeType(MimeTypes.APPLICATION_M3U8);player.setMediaItem(m.build());player.prepare();player.play();title.setText(n);status.setText("กำลังเล่น • "+u);}catch(Exception e){toast("เปิดช่องไม่ได้: "+e.getMessage());}}
 void full(){full=!full;if(full){setRequestedOrientation(android.content.pm.ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);getWindow().getDecorView().setSystemUiVisibility(5894);playerView.getLayoutParams().height=-1;playerView.requestLayout();content.setVisibility(View.GONE);bottomNav.setVisibility(View.GONE);status.setVisibility(View.GONE);}else{setRequestedOrientation(android.content.pm.ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED);getWindow().getDecorView().setSystemUiVisibility(0);playerView.getLayoutParams().height=dp(220);playerView.requestLayout();content.setVisibility(View.VISIBLE);bottomNav.setVisibility(View.VISIBLE);status.setVisibility(View.VISIBLE);}}
}
